import { describe, expect, test } from "bun:test";
import { type RetirePaths, retireYoki } from "../../../src/app/retire/retire-yoki";
import { type FakeRetireFs, fakeRetireFs } from "./fake-retire-ports";

const CLAUDE = "/home/u/.claude";
const CODEX = "/home/u/.codex";
const OMP = "/home/u/.omp/agent";
const CURSOR = "/home/u/.cursor/rules";
const PROFILES = "/repo/domains/dev/config/claude-profiles";
const OMP_EXT = "/repo/home/shared/harness/omp/extensions";

const PATHS: RetirePaths = {
  claudeDir: CLAUDE,
  codexHome: CODEX,
  ompAgentDir: OMP,
  cursorRules: CURSOR,
  claudeProfilesRoot: PROFILES,
  ompRepoExtensions: OMP_EXT,
};

const HOOKS_JSON = `${JSON.stringify(
  {
    hooks: {
      PreToolUse: [
        {
          matcher: "Bash",
          hooks: [
            {
              type: "command",
              command: "'/u/jig.ts' hooks pre-tool-use --harness codex",
              timeout: 10,
            },
          ],
        },
        {
          matcher: "Bash",
          hooks: [
            { type: "command", command: `"\${YOKI_NODE:-node}" "/y/run-with-flags.js" "pre:x"` },
          ],
        },
      ],
      Stop: [{ matcher: "*", hooks: [{ type: "command", command: "node $YOKI_ROOT/x.js" }] }],
    },
  },
  null,
  2,
)}\n`;

const CONFIG_TOML = `# yoki:begin
default_permissions = "yoki"

[permissions.yoki]
extends = ":workspace"

[features]
hooks = true

[hooks.state."${CODEX}/hooks.json:pre_tool_use:1:0"]
trusted_hash = "sha256:a"
enabled = true
# yoki:end

[projects."/repo"]
trust_level = "trusted"

[hooks.state."${CODEX}/hooks.json:stop:0:0"]
trusted_hash = "sha256:b"
enabled = true
`;

/** The inventoried machine, after `jig apply --target claude --write` replaced skills/agents/rules and commands. */
function machine(): FakeRetireFs {
  return fakeRetireFs({
    files: {
      [`${CLAUDE}/.yoki/permissions.json`]: '{"deny":[]}',
      [`${CLAUDE}/.claude-packs`]: "go\n",
      [`${CLAUDE}/settings.json`]: "{}",
      [`${CODEX}/hooks.json`]: HOOKS_JSON,
      [`${CODEX}/config.toml`]: CONFIG_TOML,
      [`${CODEX}/rules/yoki.rules`]: "# ~/.codex/rules/yoki.rules — GENERATED by yoki-switch\n",
      [`${CODEX}/rules/default.rules`]: "# mine\n",
      [`${CODEX}/.yoki/codex-manifest.json`]: JSON.stringify([
        `${CODEX}/skills/cmd-plan/SKILL.md`,
        `${CODEX}/skills/cmd-learn/SKILL.md`,
      ]),
      [`${CODEX}/.yoki/permissions.json`]: "{}",
      [`${CODEX}/skills/cmd-plan/SKILL.md`]: "---\nname: cmd-plan\n---\n",
      [`${CODEX}/skills/cmd-learn/SKILL.md`]: "---\nname: cmd-learn\n---\n",
      [`${CODEX}/skills/cmd-learn/notes.md`]: "mine\n",
      [`${CODEX}/skills/.system/x/SKILL.md`]: "codex's\n",
      [`${OMP}/yoki-hooks.json`]: "{}",
      [`${OMP}/RULES.md`]: "<!-- yoki:begin -->\n# rules\n",
      [`${OMP}/.yoki/omp-manifest.json`]: "[]",
      [`${OMP}/config.yml`]: "a: 1\n",
      [`${CURSOR}/mine.mdc`]: "mine\n",
    },
    links: {
      [`${CLAUDE}/hooks`]: `${CLAUDE}/.hooks-merged`,
      [`${CLAUDE}/.hooks-merged/git-guard.sh`]: `${PROFILES}/personal/hooks/git-guard.sh`,
      [`${CLAUDE}/.agents-merged/a.md`]: `${PROFILES}/core/agents/a.md`,
      [`${CLAUDE}/.commands-merged/plan.md`]: `${PROFILES}/core/commands/plan.md`,
      [`${CLAUDE}/scripts`]: `${CLAUDE}/.scripts-merged`,
      [`${CLAUDE}/.scripts-merged/statusline.sh`]: `${PROFILES}/personal/scripts/statusline.sh`,
      [`${CODEX}/skills/grilling`]: `${PROFILES}/core/skills/grilling/codex`,
      [`${OMP}/extensions/yoki-bridge.ts`]: `${OMP_EXT}/yoki-bridge.ts`,
      [`${OMP}/extensions/yoki-guard.ts`]: `${OMP_EXT}/yoki-guard.ts`,
      [`${OMP}/extensions/jig.ts`]: "/repo/jig/adapters/omp/src/index.ts",
      [`${CURSOR}/common-agents.md`]: `${PROFILES}/runtime/yoki/.cursor/rules/common-agents.md`,
      [`${CURSOR}/golang-testing.md`]: `${PROFILES}/runtime/yoki/.cursor/rules/golang-testing.md`,
    },
    dirs: [`${CLAUDE}/agents`, `${CLAUDE}/rules`, `${CLAUDE}/skills`],
  });
}

function byPath(report: Awaited<ReturnType<typeof retireYoki>>) {
  return new Map(report.groups.flatMap((g) => g.items).map((item) => [item.path, item.action]));
}

describe("dry-run", () => {
  test("lists every group with its evidence and removes nothing", async () => {
    const fs = machine();
    const before = { files: { ...fs.files }, links: { ...fs.links } };
    const report = await retireYoki({ paths: PATHS, write: false }, fs.retire);

    expect(report.wrote).toBe(false);
    expect(fs.log).toEqual([]);
    expect(fs.files).toEqual(before.files);
    expect(fs.links).toEqual(before.links);
    expect(report.groups.map((g) => g.harness)).toEqual(["claude", "codex", "omp", "cursor"]);

    const actions = byPath(report);
    // Claude
    expect(actions.get(`${CLAUDE}/hooks`)).toEqual({ kind: "remove-link" });
    expect(actions.get(`${CLAUDE}/.hooks-merged`)).toEqual({ kind: "remove-tree" });
    expect(actions.get(`${CLAUDE}/.agents-merged`)).toEqual({ kind: "remove-tree" });
    expect(actions.get(`${CLAUDE}/.commands-merged`)).toEqual({ kind: "remove-tree" });
    expect(actions.get(`${CLAUDE}/.scripts-merged`)?.kind).toBe("skip");
    expect(actions.get(`${CLAUDE}/.skills-merged`)).toEqual({ kind: "absent" });
    expect(actions.get(`${CLAUDE}/.yoki`)).toEqual({ kind: "remove-tree" });
    expect(actions.get(`${CLAUDE}/.claude-packs`)).toEqual({ kind: "remove-file" });
    // Codex
    expect(actions.get(`${CODEX}/hooks.json`)?.kind).toBe("rewrite");
    expect(actions.get(`${CODEX}/config.toml`)?.kind).toBe("rewrite");
    expect(actions.get(`${CODEX}/rules/yoki.rules`)).toEqual({ kind: "remove-file" });
    expect(actions.has(`${CODEX}/rules/default.rules`)).toBe(false);
    expect(actions.get(`${CODEX}/.yoki`)).toEqual({ kind: "remove-tree" });
    expect(actions.get(`${CODEX}/skills/cmd-plan/SKILL.md`)).toEqual({ kind: "remove-file" });
    expect(actions.get(`${CODEX}/skills/cmd-plan`)).toEqual({ kind: "remove-tree" });
    expect(actions.get(`${CODEX}/skills/cmd-learn`)?.kind).toBe("skip");
    expect(actions.get(`${CODEX}/skills/grilling`)).toEqual({ kind: "remove-link" });
    expect(actions.has(`${CODEX}/skills/.system`)).toBe(false);
    // omp
    expect(actions.get(`${OMP}/yoki-hooks.json`)).toEqual({ kind: "remove-file" });
    expect(actions.get(`${OMP}/RULES.md`)).toEqual({ kind: "remove-file" });
    expect(actions.get(`${OMP}/.yoki`)).toEqual({ kind: "remove-tree" });
    expect(actions.get(`${OMP}/extensions/yoki-bridge.ts`)).toEqual({ kind: "remove-link" });
    expect(actions.get(`${OMP}/extensions/yoki-guard.ts`)).toEqual({ kind: "remove-link" });
    expect(actions.has(`${OMP}/extensions/jig.ts`)).toBe(false);
    expect(actions.has(`${OMP}/config.yml`)).toBe(false);
    // Cursor
    expect(actions.get(`${CURSOR}/common-agents.md`)).toEqual({ kind: "remove-link" });
    expect(actions.get(`${CURSOR}/golang-testing.md`)).toEqual({ kind: "remove-link" });
    expect(actions.has(`${CURSOR}/mine.mdc`)).toBe(false);
    const cursor = report.groups.find((g) => g.harness === "cursor");
    expect(cursor?.notes[0]).toContain("2 links into");
    expect(cursor?.notes[0]).toContain("1 other entry left alone (mine.mdc)");

    expect(report.counts.skipped).toBe(2);
  });

  test("the rewrites say what goes and what is carried", async () => {
    const report = await retireYoki({ paths: PATHS, write: false }, machine().retire);
    const actions = byPath(report);
    const config = actions.get(`${CODEX}/config.toml`);
    expect(config?.kind).toBe("rewrite");
    if (config?.kind !== "rewrite") return;
    expect(config.backup).toBe(`${CODEX}/config.toml.pre-retire.20260923-000000`);
    expect(config.removed[0]).toContain("# yoki:begin … # yoki:end block");
    expect(config.removed).toContain(
      `[hooks.state."${CODEX}/hooks.json:stop:0:0"] (trust entry of a removed yoki handler)`,
    );
    expect(config.carried[0]).toContain("[features] lifted out of the block and kept");
    expect(config.content).toContain("[features]\nhooks = true\n");
    expect(config.content).toContain('[projects."/repo"]');
    expect(config.content).not.toContain("yoki");

    const hooks = actions.get(`${CODEX}/hooks.json`);
    if (hooks?.kind !== "rewrite") throw new Error("expected a rewrite");
    expect(hooks.removed).toHaveLength(2);
    expect(hooks.carried[0]).toContain("1 group kept");
    expect(hooks.carried).toContain("events left with no group, dropped: Stop");
  });
});

describe("--write", () => {
  test("removes what was listed, files and links first, rewrites next, directories last", async () => {
    const fs = machine();
    const report = await retireYoki({ paths: PATHS, write: true }, fs.retire);

    expect(report.wrote).toBe(true);
    expect(report.failures).toEqual([]);

    const kinds = fs.log.map((line) => line.split(" ")[0]);
    const firstRewrite = kinds.indexOf("rename");
    const firstTree = kinds.indexOf("remove-tree");
    const lastFileOrLink = Math.max(
      kinds.lastIndexOf("remove-file"),
      kinds.lastIndexOf("remove-link"),
    );
    expect(lastFileOrLink).toBeLessThan(firstRewrite);
    expect(firstRewrite).toBeLessThan(firstTree);

    // Gone.
    expect(fs.links[`${CLAUDE}/hooks`]).toBeUndefined();
    expect(fs.links[`${CLAUDE}/.hooks-merged/git-guard.sh`]).toBeUndefined();
    expect(fs.files[`${CLAUDE}/.yoki/permissions.json`]).toBeUndefined();
    expect(fs.files[`${CLAUDE}/.claude-packs`]).toBeUndefined();
    expect(fs.files[`${CODEX}/rules/yoki.rules`]).toBeUndefined();
    expect(fs.files[`${CODEX}/.yoki/codex-manifest.json`]).toBeUndefined();
    expect(fs.files[`${CODEX}/skills/cmd-plan/SKILL.md`]).toBeUndefined();
    expect(fs.links[`${CODEX}/skills/grilling`]).toBeUndefined();
    expect(fs.files[`${OMP}/RULES.md`]).toBeUndefined();
    expect(fs.links[`${OMP}/extensions/yoki-guard.ts`]).toBeUndefined();
    expect(fs.links[`${CURSOR}/common-agents.md`]).toBeUndefined();
    // Rewritten, with the original kept beside it.
    expect(fs.files[`${CODEX}/config.toml.pre-retire.20260923-000000`]).toBe(CONFIG_TOML);
    expect(fs.files[`${CODEX}/config.toml`]).toContain("[features]\nhooks = true");
    expect(fs.files[`${CODEX}/hooks.json.pre-retire.20260923-000000`]).toBe(HOOKS_JSON);
    expect(JSON.parse(fs.files[`${CODEX}/hooks.json`] ?? "")).toEqual({
      hooks: { PreToolUse: [JSON.parse(HOOKS_JSON).hooks.PreToolUse[0]] },
    });
    // Skipped and foreign: untouched.
    expect(fs.links[`${CLAUDE}/.scripts-merged/statusline.sh`]).toBeDefined();
    expect(fs.files[`${CODEX}/skills/cmd-learn/notes.md`]).toBe("mine\n");
    expect(fs.files[`${CODEX}/skills/cmd-learn/SKILL.md`]).toBeDefined();
    expect(fs.files[`${CODEX}/rules/default.rules`]).toBe("# mine\n");
    expect(fs.files[`${CODEX}/skills/.system/x/SKILL.md`]).toBeDefined();
    expect(fs.links[`${OMP}/extensions/jig.ts`]).toBeDefined();
    expect(fs.files[`${OMP}/config.yml`]).toBe("a: 1\n");
    expect(fs.files[`${CURSOR}/mine.mdc`]).toBe("mine\n");
    expect(fs.files[`${CLAUDE}/settings.json`]).toBe("{}");
  });

  test("a mismatch is skipped, and a config.toml that will not parse is not written", async () => {
    const fs = machine();
    fs.files[`${CODEX}/config.toml`] = "# yoki:begin\nx = 1\n";
    fs.files[`${CLAUDE}/.hooks-merged/notes.txt`] = "mine";
    const report = await retireYoki({ paths: PATHS, write: true }, fs.retire);
    const actions = byPath(report);
    expect(actions.get(`${CODEX}/config.toml`)?.kind).toBe("skip");
    expect(actions.get(`${CLAUDE}/.hooks-merged`)?.kind).toBe("skip");
    expect(fs.files[`${CODEX}/config.toml`]).toBe("# yoki:begin\nx = 1\n");
    expect(fs.files[`${CLAUDE}/.hooks-merged/notes.txt`]).toBe("mine");
    // The link to the staging directory still goes: it is a pointer, and the directory stays.
    expect(fs.links[`${CLAUDE}/hooks`]).toBeUndefined();
    expect(report.failures).toEqual([]);
  });

  test("a TOML validator can veto the config.toml rewrite", async () => {
    const fs = machine();
    const report = await retireYoki(
      {
        paths: PATHS,
        write: true,
        options: {
          validateToml: () => {
            throw new Error("bad toml");
          },
        },
      },
      fs.retire,
    );
    expect(byPath(report).get(`${CODEX}/config.toml`)?.kind).toBe("skip");
    expect(fs.files[`${CODEX}/config.toml`]).toBe(CONFIG_TOML);
  });

  test("an adapter refusal is recorded per item and the run continues", async () => {
    const fs = machine();
    const failing = {
      ...fs.retire,
      removeTree: async (path: string) => {
        if (path === `${CLAUDE}/.yoki`) throw new Error("refused for the test");
        return fs.retire.removeTree(path);
      },
    };
    const report = await retireYoki({ paths: PATHS, write: true }, failing);
    expect(report.failures).toEqual([{ path: `${CLAUDE}/.yoki`, error: "refused for the test" }]);
    expect(fs.dirs.has(`${CLAUDE}/agents`)).toBe(true);
    expect(fs.links[`${CLAUDE}/.agents-merged/a.md`]).toBeUndefined();
  });

  test("with nothing to remove, --write writes nothing", async () => {
    const fs = fakeRetireFs({ files: { [`${CODEX}/hooks.json`]: '{"hooks":{}}' } });
    const report = await retireYoki({ paths: PATHS, write: true }, fs.retire);
    expect(report.wrote).toBe(false);
    expect(report.counts.removals).toBe(0);
    expect(fs.log).toEqual([]);
  });
});

describe("evidence that is not there", () => {
  test("no manifest: cmd-* names fall back to the inventory's list, and the note says so", async () => {
    const fs = machine();
    delete fs.files[`${CODEX}/.yoki/codex-manifest.json`];
    fs.files[`${CODEX}/skills/cmd-mine/SKILL.md`] = "mine";
    const report = await retireYoki({ paths: PATHS, write: false }, fs.retire);
    const actions = byPath(report);
    expect(actions.get(`${CODEX}/skills/cmd-plan`)).toEqual({ kind: "remove-tree" });
    expect(actions.get(`${CODEX}/skills/cmd-mine`)?.kind).toBe("skip");
    const codex = report.groups.find((g) => g.harness === "codex");
    expect(
      codex?.notes.some((note) => note.includes("no readable .yoki/codex-manifest.json")),
    ).toBe(true);
  });

  test("an omp RULES.md without yoki's marker, and a yoki.rules without its header, stay", async () => {
    const fs = machine();
    fs.files[`${OMP}/RULES.md`] = "# my own\n";
    fs.files[`${CODEX}/rules/yoki.rules`] = "# hand-written\n";
    const report = await retireYoki({ paths: PATHS, write: true }, fs.retire);
    const actions = byPath(report);
    expect(actions.get(`${OMP}/RULES.md`)?.kind).toBe("skip");
    expect(actions.get(`${CODEX}/rules/yoki.rules`)?.kind).toBe("skip");
    expect(fs.files[`${OMP}/RULES.md`]).toBe("# my own\n");
    expect(fs.files[`${CODEX}/rules/yoki.rules`]).toBe("# hand-written\n");
  });
});
