import { describe, expect, test } from "bun:test";
import {
  eventLabel,
  isYokiGroup,
  planConfigTomlRetire,
  planHooksJsonRetire,
  removeTomlTable,
  staleTrustTables,
} from "../../../src/domain/retire/codex-config";

const HOOKS_JSON = "/home/u/.codex/hooks.json";
const YOKI = "/repo/claude-profiles/runtime/yoki/scripts/hooks";

const jigGroup = {
  matcher: "Bash",
  hooks: [
    {
      type: "command",
      command: "'/u/bun' '/u/jig.ts' hooks pre-tool-use --harness codex",
      timeout: 10,
    },
  ],
};
const orcaGroup = {
  hooks: [{ type: "command", command: "/bin/sh /u/.orca/hook.sh", timeout: 10 }],
};
const herdrGroup = {
  hooks: [{ type: "command", command: "bash '/u/herdr.sh' session", timeout: 10 }],
};
const yokiRunner = (id: string) => ({
  matcher: "*",
  hooks: [
    {
      type: "command",
      command: `"\${YOKI_NODE:-node}" "${YOKI}/run-with-flags.js" "${id}" "scripts/hooks/x.js" "standard" --harness codex`,
      timeout: 5,
    },
  ],
});
const yokiBash = {
  matcher: "Bash",
  hooks: [
    {
      type: "command",
      command: `"\${YOKI_NODE:-node}" "${YOKI}/run-bash-hook.js" --harness codex "/u/.claude/hooks/git-guard.sh"`,
    },
    { type: "command", command: "node $YOKI_ROOT/scripts/hooks/other.js" },
  ],
};

const LIVE = {
  hooks: {
    SessionStart: [herdrGroup, orcaGroup, yokiRunner("session:a")],
    PreToolUse: [jigGroup, orcaGroup, yokiRunner("pre:b"), yokiBash],
    PreCompact: [yokiRunner("pre:compact")],
    Stop: [orcaGroup],
  },
};

describe("hooks.json", () => {
  test("a group is yoki's by run-with-flags.js, $YOKI_ROOT or YOKI_ in a command", () => {
    expect(isYokiGroup(yokiRunner("x"))).toBe(true);
    expect(isYokiGroup(yokiBash)).toBe(true);
    expect(isYokiGroup({ hooks: [{ command: "node $YOKI_ROOT/x.js" }] })).toBe(true);
    expect(isYokiGroup(orcaGroup)).toBe(false);
    expect(isYokiGroup(jigGroup)).toBe(false);
    expect(isYokiGroup("nonsense")).toBe(false);
  });

  test("yoki's groups go, every other group stays in order, an emptied event is dropped", () => {
    const plan = planHooksJsonRetire(`${JSON.stringify(LIVE, null, 2)}\n`);
    expect(plan.changed).toBe(true);
    const doc = JSON.parse(plan.text) as { hooks: Record<string, unknown[]> };
    expect(doc.hooks.SessionStart).toEqual([herdrGroup, orcaGroup]);
    expect(doc.hooks.PreToolUse).toEqual([jigGroup, orcaGroup]);
    expect(doc.hooks.PreCompact).toBeUndefined();
    expect(doc.hooks.Stop).toEqual([orcaGroup]);
    expect(plan.droppedEvents).toEqual(["PreCompact"]);
    expect(plan.keptGroups).toBe(5);
    expect(plan.removed.map((h) => `${h.event}:${h.groupIndex}:${h.handlerIndex}`)).toEqual([
      "SessionStart:2:0",
      "PreToolUse:2:0",
      "PreToolUse:3:0",
      "PreToolUse:3:1",
      "PreCompact:0:0",
    ]);
    // No kept group sat behind a yoki one here, so nothing shifts.
    expect(plan.shifted).toEqual([]);
  });

  test("a kept group behind a removed one is reported as shifting", () => {
    const plan = planHooksJsonRetire(
      JSON.stringify({ hooks: { Stop: [yokiRunner("stop:a"), orcaGroup] } }),
    );
    expect(plan.shifted).toEqual([
      { event: "Stop", from: 1, to: 0, command: "/bin/sh /u/.orca/hook.sh" },
    ]);
  });

  test("other top-level keys ride through, and a file with nothing of yoki's is unchanged", () => {
    const text = `${JSON.stringify({ $schema: "x", hooks: { Stop: [orcaGroup] } }, null, 2)}\n`;
    const plan = planHooksJsonRetire(text);
    expect(plan.changed).toBe(false);
    expect(plan.text).toBe(text);
    expect(JSON.parse(plan.text)).toMatchObject({ $schema: "x" });
  });

  test("the shape jig codex register refuses is refused here", () => {
    expect(() => planHooksJsonRetire('{"hooks": {"Stop": "nope"}}')).toThrow(/must be an array/);
    expect(() => planHooksJsonRetire("[]")).toThrow(/expected an object/);
  });

  test("event labels follow Codex's trust keys", () => {
    expect(eventLabel("PreToolUse")).toBe("pre_tool_use");
    expect(eventLabel("SessionStart")).toBe("session_start");
    expect(eventLabel("UserPromptSubmit")).toBe("user_prompt_submit");
    expect(eventLabel("Stop")).toBe("stop");
  });
});

const CONFIG = `sandbox_mode = "workspace-write"

# yoki:begin
# GENERATED by yoki lib/targets/gen.js --target codex. Do not edit inside this block.
default_permissions = "yoki"
notify = ["node", "/repo/yoki/codex-notify.js"]

[permissions.yoki]
extends = ":workspace"

[permissions.yoki.filesystem]
"~/.ssh/id_*" = "deny"

[features]
hooks = true
multi_agent = true

[features.multi_agent_v2]
max_concurrent_threads_per_session = 4

[shell_environment_policy.set]
YOKI_ROOT = "/repo/yoki"

[hooks.state."${HOOKS_JSON}:session_start:2:0"]
trusted_hash = "sha256:aaa"
enabled = true

[mcp_servers.context7]
command = "npx"
args = ["-y", "@upstash/context7-mcp@1.0.14"]
# yoki:end

[projects."/repo"]
trust_level = "trusted"

[hooks.state."${HOOKS_JSON}:pre_tool_use:2:0"]
trusted_hash = "sha256:bbb"
enabled = true

[mcp_servers.serena]
command = "uvx"

# jig:begin hooks
[hooks.state."${HOOKS_JSON}:pre_tool_use:0:0"]
trusted_hash = "sha256:ccc"
enabled = true
# jig:end hooks

[sandbox_workspace_write]
network_access = false
`;

const EXPECTED = `sandbox_mode = "workspace-write"

[features]
hooks = true
multi_agent = true

[features.multi_agent_v2]
max_concurrent_threads_per_session = 4

[projects."/repo"]
trust_level = "trusted"

[mcp_servers.serena]
command = "uvx"

# jig:begin hooks
[hooks.state."${HOOKS_JSON}:pre_tool_use:0:0"]
trusted_hash = "sha256:ccc"
enabled = true
# jig:end hooks

[sandbox_workspace_write]
network_access = false
`;

describe("config.toml", () => {
  test("the block goes, [features] is lifted out, a removed handler's trust table outside the block goes, the rest is byte for byte", () => {
    const plan = planConfigTomlRetire({
      text: CONFIG,
      hooksJsonPath: HOOKS_JSON,
      removedHandlers: [
        { event: "SessionStart", groupIndex: 2, handlerIndex: 0, command: "x" },
        { event: "PreToolUse", groupIndex: 2, handlerIndex: 0, command: "y" },
      ],
    });
    expect(plan.text).toBe(EXPECTED);
    expect(plan.changed).toBe(true);
    expect(plan.carried).toEqual(["[features]", "[features.multi_agent_v2]"]);
    expect(plan.removed[0]).toMatch(/^# yoki:begin … # yoki:end block \(\d+ lines\): /);
    expect(plan.removed[0]).toContain("default_permissions, notify, [permissions.yoki]");
    expect(plan.removed[0]).toContain("[features] (kept, lifted out)");
    expect(plan.removed[0]).toContain("[mcp_servers.context7]");
    expect(plan.removed[0]).toContain("1 [hooks.state.*] trust tables of yoki's handlers");
    expect(plan.removed).toContain(
      `[hooks.state."${HOOKS_JSON}:pre_tool_use:2:0"] (trust entry of a removed yoki handler)`,
    );
    // jig's own trust table is untouched even though it is a hooks.state table.
    expect(plan.text).toContain(`[hooks.state."${HOOKS_JSON}:pre_tool_use:0:0"]`);
    expect(Bun.TOML.parse(plan.text)).toMatchObject({
      features: {
        hooks: true,
        multi_agent: true,
        multi_agent_v2: { max_concurrent_threads_per_session: 4 },
      },
      sandbox_workspace_write: { network_access: false },
    });
  });

  test("the permission tables go wherever they stand, block or not", () => {
    const text = `a = 1\n\n[permissions.yoki]\nextends = ":workspace"\n\n[permissions.yoki.filesystem]\n"~/.ssh/id_*" = "deny"\n\n[other]\nb = 2\n`;
    const plan = planConfigTomlRetire({ text, hooksJsonPath: HOOKS_JSON, removedHandlers: [] });
    expect(plan.text).toBe("a = 1\n\n[other]\nb = 2\n");
    expect(plan.removed).toEqual([
      "[permissions.yoki] table",
      "[permissions.yoki.filesystem] table",
    ]);
  });

  test("a block with no end marker is not safely editable", () => {
    expect(() =>
      planConfigTomlRetire({
        text: "# yoki:begin\nx = 1\n",
        hooksJsonPath: HOOKS_JSON,
        removedHandlers: [],
      }),
    ).toThrow(/without/);
  });

  test("a file with nothing of yoki's is unchanged", () => {
    const text = '[projects."/x"]\ntrust_level = "trusted"\n';
    const plan = planConfigTomlRetire({ text, hooksJsonPath: HOOKS_JSON, removedHandlers: [] });
    expect(plan.changed).toBe(false);
    expect(plan.text).toBe(text);
    expect(plan.removed).toEqual([]);
  });

  test("removeTomlTable takes one table, header through the blank line before the next, and no other", () => {
    const text = "[a]\nx = 1\n\n[a.b]\ny = 2\n\n[c]\nz = 3\n";
    expect(removeTomlTable(text, "[a]")).toBe("[a.b]\ny = 2\n\n[c]\nz = 3\n");
    expect(removeTomlTable(text, "[a.b]")).toBe("[a]\nx = 1\n\n[c]\nz = 3\n");
    expect(removeTomlTable(text, "[c]")).toBe("[a]\nx = 1\n\n[a.b]\ny = 2\n");
    expect(removeTomlTable(text, "[nope]")).toBe(text);
  });

  test("stale trust tables are the kept handlers' old positions that the file still names", () => {
    const text = `[hooks.state."${HOOKS_JSON}:stop:1:0"]\ntrusted_hash = "sha256:x"\n`;
    expect(
      staleTrustTables(text, HOOKS_JSON, [{ event: "Stop", from: 1, to: 0, command: "c" }]),
    ).toEqual([`[hooks.state."${HOOKS_JSON}:stop:1:…"] (now group 0)`]);
    expect(
      staleTrustTables(text, HOOKS_JSON, [{ event: "Stop", from: 3, to: 2, command: "c" }]),
    ).toEqual([]);
  });
});
