package theme

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
)

// On Omarchy the desktop, the terminal, the browser, VS Code and Omarchy's
// own apps take their colours from an Omarchy theme (its post-hooks write
// them), so Set runs `omarchy theme set` and leaves those to it.
// A theme Omarchy ships under the same family is used as it is (its colours
// and wallpapers are the author's); the rest are written as user themes,
// ~/.config/omarchy/themes/<name>/colors.toml, from the palette here.

// omarchyBundled maps a theme to the Omarchy theme of the same family.
var omarchyBundled = map[string]string{
	"catppuccin":       "catppuccin",
	"catppuccin-latte": "catppuccin-latte",
	"everforest":       "everforest",
	"gruvbox":          "gruvbox",
	"kanagawa":         "kanagawa",
	"nord":             "nord",
	"rosepine":         "rose-pine",
	"tokyonight":       "tokyo-night",
}

// omarchyWallpaperFamily names the bundled theme whose wallpapers a
// generated theme borrows when the checkout has none of its own.
var omarchyWallpaperFamily = map[string]string{
	"everforest-light": "everforest",
	"tokyonight-day":   "tokyo-night",
}

func omarchyName(name string) string {
	if o, ok := omarchyBundled[name]; ok {
		return o
	}
	return name
}

func (e Env) omarchy() bool { return e.Has != nil && e.Has("omarchy") }

// omarchyPath is where Omarchy is installed: $OMARCHY_PATH, which Omarchy's
// env-bootstrap sets to /usr/share/omarchy outside its dev mode.
func (e Env) omarchyPath() string {
	if e.Getenv != nil {
		if p := e.Getenv("OMARCHY_PATH"); p != "" {
			return p
		}
	}
	return "/usr/share/omarchy"
}

// colorsTOML is Omarchy's colors.toml for a palette. Omarchy's keys are
// base16-like; ours are Catppuccin's, so each key takes its nearest role.
func colorsTOML(p Palette) string {
	h := func(key string) string { return "#" + p.Hex(key) }
	lighter := "surface0"
	for _, k := range []string{"surface0", "surface1", "surface2"} {
		if p.Hex(k) != p.Hex("base") {
			lighter = k
			break
		}
	}
	rows := [][2]string{
		{"mode", p.Variant()},
		{"accent", h("blue")},
		{"selection", h("surface1")},
		{"muted", h("overlay0")},
		{"background", h("base")},
		{"dark_background", h("mantle")},
		{"darker_background", h("crust")},
		{"lighter_background", h(lighter)},
		{"foreground", h("text")},
		{"dark_foreground", h("overlay2")},
		{"light_foreground", h("subtext1")},
		{"bright_foreground", h("text")},
		{"red", h("red")},
		{"yellow", h("yellow")},
		{"orange", h("peach")},
		{"green", h("green")},
		{"cyan", h("teal")},
		{"blue", h("blue")},
		{"magenta", h("mauve")},
		{"brown", "#" + mix(p.Hex("peach"), p.Hex("crust"))},
		{"bright_red", h("maroon")},
		{"bright_yellow", h("yellow")},
		{"bright_green", h("green")},
		{"bright_cyan", h("sky")},
		{"bright_blue", h("blue")},
		{"bright_magenta", h("pink")},
	}
	var b strings.Builder
	b.WriteString("# Generated by dotctl from home/shared/theme/themes; edits are overwritten.\n")
	for _, r := range rows {
		fmt.Fprintf(&b, "%s = %q\n", r[0], r[1])
	}
	return b.String()
}

// mix is the midpoint of two hex colours.
func mix(a, b string) string {
	x, errA := strconv.ParseUint(a, 16, 32)
	y, errB := strconv.ParseUint(b, 16, 32)
	if errA != nil || errB != nil {
		return a
	}
	ch := func(v uint64, shift uint) uint64 { return v >> shift & 0xff }
	return fmt.Sprintf("%02x%02x%02x", (ch(x, 16)+ch(y, 16))/2, (ch(x, 8)+ch(y, 8))/2, (ch(x, 0)+ch(y, 0))/2)
}

// writeOmarchyThemes writes a user theme for every palette Omarchy does not
// ship: colors.toml, and backgrounds/ linking the checkout's wallpaper, or
// the family's bundled ones when the checkout has none.
func writeOmarchyThemes(e Env) error {
	names, err := List(e)
	if err != nil {
		return err
	}
	for _, name := range names {
		if _, bundled := omarchyBundled[name]; bundled {
			continue
		}
		p, err := readPalette(e.repo(Apps[0].Source(name)))
		if err != nil {
			return err
		}
		dir := filepath.Join(e.Home, ".config", "omarchy", "themes", name)
		if err := writeIfChanged(filepath.Join(dir, "colors.toml"), []byte(colorsTOML(p))); err != nil {
			return err
		}
		if err := linkBackgrounds(e, name, filepath.Join(dir, "backgrounds")); err != nil {
			return err
		}
	}
	return nil
}

func writeIfChanged(path string, b []byte) error {
	if old, err := os.ReadFile(path); err == nil && bytes.Equal(old, b) {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return writeAtomic(path, b)
}

// linkBackgrounds makes dir hold links to the theme's wallpapers, replacing
// the links it held before and leaving anything else there alone.
func linkBackgrounds(e Env, name, dir string) error {
	images := wallpapersOf(e, name)
	if len(images) == 0 {
		e.warn("omarchy: no wallpaper for '%s'", name)
		return nil
	}
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}
	old, err := os.ReadDir(dir)
	if err != nil {
		return err
	}
	for _, d := range old {
		if d.Type()&os.ModeSymlink != 0 {
			if err := os.Remove(filepath.Join(dir, d.Name())); err != nil {
				return err
			}
		}
	}
	for _, img := range images {
		if err := os.Symlink(img, filepath.Join(dir, filepath.Base(img))); err != nil && !os.IsExist(err) {
			return err
		}
	}
	return nil
}

func wallpapersOf(e Env, name string) []string {
	for _, ext := range []string{"jpg", "jpeg", "png"} {
		if img := e.repo("home/shared/theme/wallpapers/" + name + "." + ext); exists(img) {
			return []string{img}
		}
	}
	family, ok := omarchyWallpaperFamily[name]
	if !ok {
		return nil
	}
	dir := filepath.Join(e.omarchyPath(), "themes", family, "backgrounds")
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil
	}
	var images []string
	for _, d := range entries {
		if !d.IsDir() {
			images = append(images, filepath.Join(dir, d.Name()))
		}
	}
	return images
}

// applyOmarchy switches Omarchy's theme; it also sets the wallpaper, from
// the theme's backgrounds.
func applyOmarchy(e Env, name string) error {
	if !e.omarchy() || e.Run == nil {
		return nil
	}
	if _, bundled := omarchyBundled[name]; !bundled {
		if err := writeOmarchyThemes(e); err != nil {
			return err
		}
	}
	return e.Run("omarchy", "theme", "set", omarchyName(name))
}
