# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@dqbd/tiktoken-1.0.22" = {
      name = "_at_dqbd_slash_tiktoken";
      packageName = "@dqbd/tiktoken";
      version = "1.0.22";
      src = fetchurl {
        url = "https://registry.npmjs.org/@dqbd/tiktoken/-/tiktoken-1.0.22.tgz";
        sha512 = "RYhO8xeHkMNX5Ixqf4M1Ve3siCYJY/dI0yLnlX4M4oIEDOvjMIQ+E+3OUpAaZcWTaMtQJzGcDAghYfllpx3i/w==";
      };
    };
    "aicommits-1.11.0" = {
      name = "aicommits";
      packageName = "aicommits";
      version = "1.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/aicommits/-/aicommits-1.11.0.tgz";
        sha512 = "YRy+M230yIuJ+j3YqXRAtAbmR2rJSzST5TbJASPXqaIh7kMN477DGQS1cwqwTJeBdMXKBJrWJAgVd//LkoA4Wg==";
      };
    };
  };
  args = {
    name = "dotfiles-node-packages";
    packageName = "dotfiles-node-packages";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."@dqbd/tiktoken-1.0.22"
      sources."aicommits-1.11.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in
{
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src = nix-gitignore.gitignoreSourcePure [
        "*"
        "!package.json"
        "!package-lock.json"
      ] args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
