#!/bin/bash

# Catppuccin Colors
# Active: Red -> Maroon
# Inactive: Blue -> Sapphire
options=(
    style=round
    width=7.0
    hidpi=on
    active_color="gradient(top_left=0xfff38ba8,bottom_right=0xffeba0ac)"
    inactive_color="gradient(top_left=0xff89b4fa,bottom_right=0xff74c7ec)"
)

borders "${options[@]}" 