name: 'Tokyo Night Day'
accent: '#2e7de9'
background: '#e1e2e7'
foreground: '#3760bf'
cursor: '#3760bf'
selection: '#b6bfe2'
selection_foreground: '#3760bf'
details: lighter
terminal_colors:
  normal:
    black: '#b6bfe2'
    red: '#f52a65'
    green: '#587539'
    yellow: '#8c6c3e'
    blue: '#2e7de9'
    magenta: '#9854f1'
    cyan: '#07879d'
    white: '#6172b0'
  bright:
    black: '#a8aecb'
    red: '#f52a65'
    green: '#587539'
    yellow: '#8c6c3e'
    blue: '#2e7de9'
    magenta: '#9854f1'
    cyan: '#07879d'
    white: '#848cb5'
