# Catppuccin Mocha Custom Theme for Warp
# Based on WezTerm Catppuccin Mocha color palette

name: 'Catppuccin Mocha Custom'

# Main UI colors
accent: '#cba6f7'         # mauve
background: '#1e1e2e'     # base
foreground: '#cdd6f4'     # text
cursor: '#f5e0dc'         # rosewater
selection: '#f5e0dc'      # rosewater
selection_foreground: '#1e1e2e'  # base

# Use darker details for a dark theme
details: darker

# Terminal colors - ANSI colors
terminal_colors:
  normal:
    black: '#45475a'      # surface1
    red: '#f38ba8'
    green: '#a6e3a1'
    yellow: '#f9e2af'
    blue: '#89b4fa'
    magenta: '#f5c2e7'    # pink
    cyan: '#94e2d5'       # teal
    white: '#bac2de'      # subtext1
  bright:
    black: '#585b70'      # surface2
    red: '#f38ba8'
    green: '#a6e3a1'
    yellow: '#f9e2af'
    blue: '#89b4fa'
    magenta: '#f5c2e7'    # pink
    cyan: '#94e2d5'       # teal
    white: '#a6adc8'      # subtext0

# Optional: Background image for transparency effect
# Replace with your preferred background image path if desired
# background_image: 
#   path: '~/path/to/background.jpg'
#   opacity: 0.05  # Low opacity for subtle effect (0.95 window opacity equivalent)