# One Dark
set -g @theme_accent  "#61afef"
set -g @theme_accent2 "#98c379"
set -g @theme_fg      "#abb2bf"
set -g @theme_muted   "#5c6370"
set -g @theme_surface "#3e4452"
set -g @theme_crust   "#282c34"
set -g @theme_warn    "#e06c75"
