-- AstroVim colorscheme - auto-generated by theme-switch
return {
  { "catppuccin/nvim", name = "catppuccin", lazy = true },
  { "folke/tokyonight.nvim", lazy = true },
  { "rebelot/kanagawa.nvim", lazy = true },
  { "ellisonleao/gruvbox.nvim", lazy = true },
  { "Mofiqul/dracula.nvim", lazy = true },
  { "rose-pine/neovim", name = "rose-pine", lazy = true },
  { "sainnhe/everforest", lazy = true },
  { "navarasu/onedark.nvim", lazy = true },
  { "maxmx03/solarized.nvim", lazy = true },
  { "shaunsingh/nord.nvim", lazy = true },
  {
    "AstroNvim/astrocore",
    opts = {
      colorscheme = "kanagawa",
    },
  },
}

