name: 'Dracula'
accent: '#bd93f9'
background: '#282a36'
foreground: '#f8f8f2'
cursor: '#ffb86c'
selection: '#44475a'
selection_foreground: '#f8f8f2'
details: darker
terminal_colors:
  normal:
    black: '#383a59'
    red: '#ff5555'
    green: '#50fa7b'
    yellow: '#f1fa8c'
    blue: '#bd93f9'
    magenta: '#ff79c6'
    cyan: '#8be9fd'
    white: '#e0e0e0'
  bright:
    black: '#44475a'
    red: '#ff6e6e'
    green: '#50fa7b'
    yellow: '#f1fa8c'
    blue: '#bd93f9'
    magenta: '#ff79c6'
    cyan: '#8be9fd'
    white: '#bfbfbf'
