name: 'Solarized Dark'
accent: '#268bd2'
background: '#002b36'
foreground: '#839496'
cursor: '#839496'
selection: '#073642'
selection_foreground: '#839496'
details: darker
terminal_colors:
  normal:
    black: '#073642'
    red: '#dc322f'
    green: '#859900'
    yellow: '#b58900'
    blue: '#268bd2'
    magenta: '#d33682'
    cyan: '#2aa198'
    white: '#93a1a1'
  bright:
    black: '#586e75'
    red: '#cb4b16'
    green: '#586e75'
    yellow: '#657b83'
    blue: '#839496'
    magenta: '#6c71c4'
    cyan: '#2aa198'
    white: '#fdf6e3'
