'use strict';

/**
 * Builds the `[mcp_servers.<name>]` TOML tables appended into Codex's
 * `config.toml` managed block (task T13, consumed by
 * `lib/targets/codex-config-toml.js` via T9's `toml-block` op — see
 * `buildRulesAndConfigOperations` in `lib/targets/codex.js` for the wiring).
 *
 * Field shape mirrors the hand-written entries this repo already ships in
 * `domains/dev/config/codex/config.toml.template` (an http server sets an
 * empty `command = ""` alongside `type = "http"` and `url` — kept exactly
 * as that already-working config does it, rather than guessing at a
 * different shape).
 *
 * A same-named `[mcp_servers.<name>]` table already declared OUTSIDE the
 * managed block (a hand-added server, or a pre-T13 `codex mcp add` entry)
 * is left alone rather than overwritten — the caller surfaces the resulting
 * warning through gen.js's `plan().warnings`, same as every other codex.js
 * warning.
 */

function tomlString(value) {
  return JSON.stringify(String(value));
}

/** Applies this server's 'codex' targetOverrides, if any. */
function applyCodexOverride(server) {
  const override = server.targetOverrides && server.targetOverrides.codex;
  return override ? { ...server, ...override } : server;
}

/** @param {object} server a resolved server (after 'codex' targetOverrides) */
function toTomlTable(server) {
  const lines = [`[mcp_servers.${server.name}]`];

  if (server.transport === 'http') {
    lines.push('command = ""');
    lines.push('type = "http"');
    lines.push(`url = ${tomlString(server.url)}`);
  } else {
    lines.push('type = "stdio"');
    lines.push(`command = ${tomlString(server.command)}`);
    lines.push(`args = [${(server.args || []).map(tomlString).join(', ')}]`);
  }

  const envEntries = Object.entries(server.env || {});
  if (envEntries.length) {
    lines.push(`[mcp_servers.${server.name}.env]`);
    for (const [key, value] of envEntries) lines.push(`${key} = ${tomlString(value)}`);
  }

  return lines.join('\n');
}

const MCP_TABLE_HEADER_RE = /^\[mcp_servers\.([^\].\s]+)\]/gm;

/** Names of every `[mcp_servers.<name>]` table appearing in `text` (used
 * only against the config.toml content OUTSIDE our managed block). */
function findServerNamesInText(text) {
  const names = new Set();
  const re = new RegExp(MCP_TABLE_HEADER_RE);
  let match;
  while ((match = re.exec(String(text || '')))) names.add(match[1]);
  return names;
}

/**
 * @param {Array<object>} mergedServers canonical, already core→packs→personal
 *   merged + `{{HOME}}`-resolved servers (lib/mcp-inventory/source.js
 *   loadAndMerge + resolveHome)
 * @param {string} existingOutsideBlock the config.toml content OUTSIDE our
 *   managed block (`lib/targets/managed-block.js` extractBlock's `after`)
 * @returns {{toml: string, warnings: string[]}}
 */
function buildMcpServersToml(mergedServers, existingOutsideBlock) {
  const conflicting = findServerNamesInText(existingOutsideBlock);
  const warnings = [];
  const tables = [];

  for (const server of mergedServers) {
    if (!server.targets || server.targets.codex !== true) continue;

    if (conflicting.has(server.name)) {
      warnings.push(
        `codex: [mcp_servers.${server.name}] is already declared outside the managed block — left alone, not regenerated by yoki`
      );
      continue;
    }

    tables.push(toTomlTable(applyCodexOverride(server)));
  }

  return { toml: tables.join('\n\n'), warnings };
}

module.exports = { toTomlTable, applyCodexOverride, findServerNamesInText, buildMcpServersToml };
