/**
 * `~/.omp/agent/agents/<name>.md`, one generated file per `agents/*.md`.
 *
 * omp's custom agent is the same shape as the source — Markdown with YAML
 * frontmatter, the body as the system prompt — so the body is copied through
 * verbatim and only the frontmatter is translated. The contract is omp's
 * task-agent discovery
 * (https://github.com/can1357/oh-my-pi/blob/main/docs/task-agent-discovery.md,
 * "Role-backed custom agents": "OMP discovers user agents from
 * `~/.omp/agent/agents/*.md`"; "Agent definition shape": "required `name`,
 * `description`, and `systemPrompt`", "`tools` accepts CSV or array; if
 * provided, `yield` is auto-added", "`model` accepts one selector, CSV, or
 * an array"), and `parseAgentFields()` in
 * `packages/coding-agent/src/discovery/helpers.ts`, which drops a file whose
 * `name` or `description` is missing.
 *
 * - `name` and `description` are copied verbatim, as YAML double-quoted
 *   scalars (a JSON string is one).
 * - `tools:` names Claude Code tools; omp's are the ids of
 *   `packages/coding-agent/src/tools/builtin-names.ts` (`BUILTIN_TOOL_NAMES`),
 *   and its `normalizeToolNames` lower-cases a name only when the result is
 *   one of those ids — `Read` becomes `read`, but `WebSearch`, `TodoWrite`
 *   and `MultiEdit` would pass through as unknown tools and restrict the
 *   agent to nothing. So the list is translated here through a fixed table
 *   and a name with no omp tool is left out and reported: a shorter list
 *   only narrows the agent, which is the safe direction. When nothing
 *   survives, the key is omitted and omp grants its default set.
 * - `model:` is a Claude tier; omp wants a provider-qualified selector
 *   (`openai/gpt-5.4:high`) or a `modelRoles` alias (`@review`). Looked up
 *   in a map the caller supplies, left out and reported otherwise, exactly
 *   as the Codex target does. The generator never invents one.
 *
 * Pure: a definition in, the file's text out.
 */

import type { AgentDefinition, ModelChoice } from "../claude/agent-definition";

/** Where the format is fixed, for the header comment. */
export const OMP_AGENTS_DOC_URL =
  "https://github.com/can1357/oh-my-pi/blob/main/docs/task-agent-discovery.md";

/**
 * Claude Code tool name → omp tool id. Every right-hand side is in omp's
 * `BUILTIN_TOOL_NAMES`. `WebFetch` maps to `read` because omp has no fetch
 * tool: `read` "Read files, directories, archives, SQLite databases, internal
 * resources, images, documents, and URLs through one `path` string"
 * (docs/tools/read.md), which is also why jig's omp guard judges an http(s)
 * `read` as a fetch (`adapters/omp/src/map.ts`). `Agent` is Claude Code's
 * newer name for `Task`. Notebook tools and `Skill` have no omp id.
 */
export const CLAUDE_TO_OMP_TOOL: Readonly<Record<string, string>> = {
  Read: "read",
  Grep: "grep",
  Glob: "glob",
  Bash: "bash",
  Edit: "edit",
  MultiEdit: "edit",
  Write: "write",
  Task: "task",
  Agent: "task",
  TodoWrite: "todo",
  TodoRead: "todo",
  WebSearch: "web_search",
  WebFetch: "read",
};

export interface OmpToolTranslation {
  /** omp ids, deduplicated, in source order. */
  readonly tools: readonly string[];
  /** Source names with no omp tool, in source order. */
  readonly unmapped: readonly string[];
}

export function translateTools(tools: readonly string[]): OmpToolTranslation {
  const mapped: string[] = [];
  const unmapped: string[] = [];
  for (const name of tools) {
    const id = CLAUDE_TO_OMP_TOOL[name];
    if (id === undefined) unmapped.push(name);
    else if (!mapped.includes(id)) mapped.push(id);
  }
  return { tools: mapped, unmapped };
}

/** A YAML double-quoted scalar: JSON's string syntax is a subset of it. */
export function yamlString(value: string): string {
  return JSON.stringify(value);
}

export interface OmpAgentInput {
  readonly definition: AgentDefinition;
  readonly model: ModelChoice;
  readonly tools: OmpToolTranslation;
  /** Absolute path of the source `agents/<name>.md`, for the header comment. */
  readonly sourcePath: string;
}

/**
 * The whole `<name>.md`: frontmatter with the two required keys, `model`
 * only when mapped, `tools` only when any survived, then the body verbatim.
 * The provenance line is a YAML comment inside the frontmatter, so the body
 * — omp's system prompt — carries nothing the source did not.
 */
export function renderOmpAgent(input: OmpAgentInput): string {
  const { definition, model, tools } = input;
  const lines = [
    "---",
    `# generated by jig apply --target omp from ${input.sourcePath} — edit the source, not this file`,
    `# format: ${OMP_AGENTS_DOC_URL}`,
    `name: ${yamlString(definition.name)}`,
    `description: ${yamlString(definition.description)}`,
    ...(model.kind === "mapped" ? [`model: ${yamlString(model.model)}`] : []),
    ...(tools.tools.length > 0 ? [`tools: [${tools.tools.join(", ")}]`] : []),
    "---",
    "",
    definition.body,
  ];
  return `${lines.join("\n")}\n`;
}

/** The frontmatter alone (between the fences), for a caller that validates it as YAML. */
export function ompAgentFrontmatter(text: string): string {
  const match = /^---\r?\n([\s\S]*?)\r?\n---\r?\n/.exec(text);
  return match?.[1] ?? "";
}

/** `research.md` → `research.md`; the file name, not the frontmatter `name`, keys the destination. */
export function ompAgentFileName(sourceFile: string): string {
  return sourceFile;
}
