import { describe, expect, test } from "bun:test";
import {
  OMP_EXTENSION_LINK_NAME,
  type OmpApplyOptions,
  type OmpApplyPaths,
  applyOmp,
} from "../../../src/app/apply/apply-omp";
import type { OmpApplyPorts } from "../../../src/app/apply/ports";
import { type FakeClaudeFs, type FakeClaudeFsSeed, fakeClaudeFs } from "./fake-claude-ports";

const H = "/repo/llm/harness";
const OLD = "/repo/config/claude-profiles";
const OMP = "/home/u/.omp/agent";
const AGENTS_SKILLS = "/home/u/.agents/skills";
const EXTENSION = `${H}/jig/adapters/omp/src/index.ts`;

const PATHS: OmpApplyPaths = {
  harnessRoot: H,
  mcpServers: `${H}/mcp/servers.json`,
  formerSkillRoots: [OLD],
  agentsSkills: AGENTS_SKILLS,
  agentDir: OMP,
  agentsDir: `${OMP}/agents`,
  mcpJson: `${OMP}/mcp.json`,
  configYml: `${OMP}/config.yml`,
  extensionsDir: `${OMP}/extensions`,
  extensionTarget: EXTENSION,
  home: "/home/u",
};

const OPTIONS: OmpApplyOptions = {
  ompModels: {},
  validateFrontmatter: (yaml) => {
    Bun.YAML.parse(yaml);
  },
};

const MCP_SOURCE = JSON.stringify({
  schemaVersion: "jig.mcp.v1",
  servers: [
    {
      name: "serena",
      transport: "stdio",
      command: "uvx",
      args: ["serena", "--context", "claude-code"],
      targets: { claude: true, omp: true },
      targetOverrides: { omp: { args: ["serena", "--context", "codex"] } },
    },
    {
      name: "codebase-memory-mcp",
      transport: "stdio",
      command: "{{HOME}}/bin/cmm",
      args: [],
      targets: { claude: true, omp: true },
    },
    {
      name: "figma-remote",
      transport: "http",
      url: "https://mcp.figma.com/mcp",
      targets: { omp: true },
    },
    { name: "claude-only", transport: "stdio", command: "x", targets: { claude: true } },
  ],
});

const RESEARCH_AGENT =
  '---\nname: research\ndescription: Industry survey.\ntools: ["Read", "WebFetch", "NotebookEdit"]\nmodel: sonnet\n---\n\nSurvey first, judge second.\n';
const SCOUT_AGENT =
  "---\nname: scout\ndescription: Cheap lookups.\ntools: [Read]\nmodel: haiku\n---\n\nLook things up.\n";

/** The sources every test starts from; the destination side is the seed. */
function fakePorts(seed: FakeClaudeFsSeed = {}): FakeClaudeFs {
  return fakeClaudeFs({
    ...seed,
    files: {
      [PATHS.mcpServers]: MCP_SOURCE,
      [`${H}/skills/README.md`]: "# skills\n",
      [`${H}/skills/writeup/SKILL.md`]: "---\nname: writeup\n---\n",
      [`${H}/skills/grilling/SKILL.md`]: "---\nname: grilling\n---\n",
      [`${H}/agents/research.md`]: RESEARCH_AGENT,
      [`${H}/agents/scout.md`]: SCOUT_AGENT,
      [EXTENSION]: "export default function () {}\n",
      ...seed.files,
    },
  });
}

const run = (ports: OmpApplyPorts, write = false) =>
  applyOmp({ paths: PATHS, options: OPTIONS, write }, ports);

const LIVE_MCP_JSON = `${JSON.stringify(
  {
    mcpServers: {
      "codebase-memory-mcp": { type: "stdio", command: "/home/u/bin/cmm" },
      serena: { type: "stdio", command: "uvx", args: ["serena", "--context", "codex"] },
      mine: { type: "http", url: "https://mine.example/mcp" },
    },
    disabledServers: ["mine"],
  },
  null,
  2,
)}\n`;

const YOKI_RESEARCH_MD =
  '---\nname: research\ndescription: "Industry survey."\nmodel: anthropic/claude-sonnet-5\ntools: [read]\n---\n\nSurvey first, judge second.\n';

/** The machine yoki-switch left: its agent files, its mcp.json, its extension links, its own files. */
const YOKI_SWITCH_MACHINE: FakeClaudeFsSeed = {
  files: {
    [`${PATHS.agentsDir}/research.md`]: YOKI_RESEARCH_MD,
    [`${PATHS.agentsDir}/css-perf-reviewer.md`]: "---\nname: css-perf-reviewer\n---\n",
    [PATHS.mcpJson]: LIVE_MCP_JSON,
    [`${PATHS.extensionsDir}/orca-prefill.ts`]: "export default function () {}\n",
    [`${OMP}/yoki-hooks.json`]: "{}",
    [`${OMP}/RULES.md`]: "<!-- yoki:begin -->\n",
    [`${OMP}/.yoki/omp-manifest.json`]: "{}",
    [`${OMP}/config.yml`]: "# GENERATED by yoki lib/targets/gen.js --target omp.\n",
  },
  links: {
    [`${AGENTS_SKILLS}/writeup`]: `${OLD}/core/skills/writeup`,
    [`${AGENTS_SKILLS}/retired`]: `${OLD}/packs/go/skills/retired`,
    [`${PATHS.extensionsDir}/yoki-bridge.ts`]: "/repo/config/omp/extensions/yoki-bridge.ts",
    [`${PATHS.extensionsDir}/yoki-guard.ts`]: "/repo/config/omp/extensions/yoki-guard.ts",
  },
};

describe("dry-run is the default", () => {
  test("nothing is written, the outcome is the plan", async () => {
    const { ports, files, links, manifest } = fakePorts();
    const report = await run(ports);

    expect(report.wrote).toBe(false);
    expect(report.outcome).toBe("write");
    expect(files[PATHS.mcpJson]).toBeUndefined();
    expect(files[`${PATHS.agentsDir}/research.md`]).toBeUndefined();
    expect(links).toEqual({});
    expect(manifest).toEqual({});
  });
});

describe("the cross-harness skills mount", () => {
  test("is the same plan the codex target makes, and says this run was omp's", async () => {
    const { ports } = fakePorts(YOKI_SWITCH_MACHINE);
    const report = await run(ports);

    expect(report.agentsSkillsDir.target).toBe("omp");
    expect(report.agentsSkillsDir.selection.linked).toEqual(["grilling", "writeup"]);
    expect(
      report.agentsSkillsDir.entries.map((e) =>
        e.kind === "link"
          ? `${e.name}:${e.plan.state}`
          : `${e.name}:${e.kind}${e.kind === "stale" ? `:${e.reason}` : ""}`,
      ),
    ).toEqual(["grilling:create", "writeup:replace", "retired:stale:former-tree"]);
  });

  test("a second target's run finds every link ok", async () => {
    const { ports } = fakePorts();
    await run(ports, true);
    const again = await run(ports);
    expect(
      again.agentsSkillsDir.entries.every((e) => e.kind === "link" && e.plan.state === "ok"),
    ).toBe(true);
  });
});

describe("the generated agent files", () => {
  test("one <name>.md per agents/*.md in omp's frontmatter, tools mapped, the gaps counted per tier and per tool", async () => {
    const { ports } = fakePorts();
    const { agents } = await run(ports);

    expect(agents.files.map((f) => `${f.name}:${f.outcome}`)).toEqual([
      "research.md:write",
      "scout.md:write",
    ]);
    const research = agents.files[0];
    expect(research?.content).toContain('name: "research"');
    expect(research?.content).toContain('description: "Industry survey."');
    expect(research?.content).toContain("tools: [read]");
    expect(research?.content).not.toContain("model:");
    expect(research?.content.endsWith("---\n\nSurvey first, judge second.\n")).toBe(true);
    expect(research?.tools).toEqual({ tools: ["read"], unmapped: ["NotebookEdit"] });
    expect(research?.model).toEqual({ kind: "unmapped", tier: "sonnet" });
    expect(agents.unmappedTiers).toEqual([
      { tier: "sonnet", count: 1 },
      { tier: "haiku", count: 1 },
    ]);
    expect(agents.unmappedTools).toEqual([{ tool: "NotebookEdit", count: 1 }]);
  });

  test("a mapped tier lands in `model`; an unmapped one is never guessed", async () => {
    const { ports } = fakePorts();
    const report = await applyOmp(
      {
        paths: PATHS,
        options: { ...OPTIONS, ompModels: { sonnet: { model: "@review" } } },
        write: false,
      },
      ports,
    );
    const [research, scout] = report.agents.files;
    expect(research?.content).toContain('model: "@review"');
    expect(scout?.content).not.toContain("model:");
    expect(report.agents.unmappedTiers).toEqual([{ tier: "haiku", count: 1 }]);
  });

  test("an agent's own models.omp wins over the table; a mapping's reasoningEffort is not written", async () => {
    const { ports } = fakePorts({
      files: {
        [`${H}/agents/scout.md`]:
          '---\nname: scout\ndescription: Cheap lookups.\nmodel: haiku\nmodels: { omp: { model: "@cheap", reasoningEffort: "low" } }\n---\n\nLook things up.\n',
      },
    });
    const report = await run(ports);
    const scout = report.agents.files.find((file) => file.name === "scout.md");
    expect(scout?.model).toEqual({
      kind: "mapped",
      tier: "haiku",
      model: "@cheap",
      reasoningEffort: "low",
      override: true,
    });
    expect(scout?.content).toContain('model: "@cheap"');
    expect(scout?.content).not.toContain("low");
    expect(report.agents.unmappedTiers).toEqual([{ tier: "sonnet", count: 1 }]);
  });

  test("a malformed models: block is an error naming the file, not a dropped override", async () => {
    const { ports } = fakePorts({
      files: {
        [`${H}/agents/scout.md`]: "---\nname: scout\nmodels:\n  omp:\n    effort: low\n---\nx\n",
      },
    });
    expect(run(ports)).rejects.toThrow(
      "jig apply --target omp: agents/scout.md: scout.md: models.omp",
    );
  });

  test("yoki's same-named files are kept aside on first write; files no source produces are not jig's", async () => {
    const { ports, files } = fakePorts(YOKI_SWITCH_MACHINE);
    const dry = await run(ports);
    expect(dry.agents.foreign).toEqual([{ name: "css-perf-reviewer.md", what: "a regular file" }]);
    expect(dry.agents.files[0]).toMatchObject({
      name: "research.md",
      outcome: "write",
      backupPath: `${PATHS.agentsDir}/research.md.pre-jig.20260923-000000`,
    });

    const report = await run(ports, true);
    expect(report.wrote).toBe(true);
    expect(files[`${PATHS.agentsDir}/research.md.pre-jig.20260923-000000`]).toBe(YOKI_RESEARCH_MD);
    expect(files[`${PATHS.agentsDir}/research.md`]).toBe(dry.agents.files[0]?.content);
    expect(files[`${PATHS.agentsDir}/css-perf-reviewer.md`]).toBe(
      "---\nname: css-perf-reviewer\n---\n",
    );
  });

  test("a hand edit after jig wrote one is a conflict for the whole delivery", async () => {
    const { ports, files, links } = fakePorts();
    await run(ports, true);
    files[`${PATHS.agentsDir}/scout.md`] = "---\nname: scout\ndescription: edited\n---\nx\n";
    delete links[`${AGENTS_SKILLS}/writeup`];

    const report = await run(ports, true);
    expect(report.outcome).toBe("conflict");
    expect(report.wrote).toBe(false);
    expect(report.message).toContain("agents/scout.md");
    expect(links[`${AGENTS_SKILLS}/writeup`]).toBeUndefined();
  });

  test("a frontmatter the validator refuses stops the run before anything is written", async () => {
    const { ports, files } = fakePorts();
    await expect(
      applyOmp(
        {
          paths: PATHS,
          options: {
            ...OPTIONS,
            validateFrontmatter: () => {
              throw new Error("refused");
            },
          },
          write: true,
        },
        ports,
      ),
    ).rejects.toThrow("refused");
    expect(files[`${PATHS.agentsDir}/research.md`]).toBeUndefined();
  });
});

describe("mcp.json", () => {
  test("jig's entries with overrides and {{HOME}}; the hand-added server and disabledServers carried through", async () => {
    const { ports, files } = fakePorts(YOKI_SWITCH_MACHINE);
    const dry = await run(ports);
    expect(dry.mcpJson.servers).toEqual(["serena", "codebase-memory-mcp", "figma-remote"]);
    expect(dry.mcpJson.foreign).toEqual(["mine"]);
    expect(dry.mcpJson.carried).toEqual(["disabledServers"]);
    expect(dry.mcpJson.outcome).toBe("write");
    expect(dry.mcpJson.diff).toContain('+      "url": "https://mcp.figma.com/mcp"');

    await run(ports, true);
    const written = JSON.parse(files[PATHS.mcpJson] ?? "") as {
      $schema: string;
      mcpServers: Record<string, Record<string, unknown>>;
      disabledServers: string[];
    };
    expect(written.$schema).toContain("mcp-schema.json");
    expect(Object.keys(written.mcpServers)).toEqual([
      "serena",
      "codebase-memory-mcp",
      "figma-remote",
      "mine",
    ]);
    expect(written.mcpServers.serena).toEqual({
      type: "stdio",
      command: "uvx",
      args: ["serena", "--context", "codex"],
    });
    expect(written.mcpServers["codebase-memory-mcp"]).toEqual({
      type: "stdio",
      command: "/home/u/bin/cmm",
    });
    expect(written.mcpServers.mine).toEqual({ type: "http", url: "https://mine.example/mcp" });
    expect(written.disabledServers).toEqual(["mine"]);
    expect(files[PATHS.mcpJson]).not.toContain("claude-only");
  });

  test("omp adding a server by /mcp add after jig wrote is not a conflict: jig's entries are what is compared", async () => {
    const { ports, files } = fakePorts();
    await run(ports, true);
    const current = JSON.parse(files[PATHS.mcpJson] ?? "") as {
      mcpServers: Record<string, unknown>;
    };
    current.mcpServers.added = { type: "stdio", command: "added" };
    files[PATHS.mcpJson] = JSON.stringify(current, null, 2);

    const report = await run(ports, true);
    expect(report.outcome).toBe("noop");
    expect(report.mcpJson.foreign).toEqual(["added"]);
    expect(files[PATHS.mcpJson]).toContain('"added"');
  });

  test("a /mcp disable on a jig server edits jig's entry: a conflict that names the way out", async () => {
    const { ports, files } = fakePorts();
    await run(ports, true);
    files[PATHS.mcpJson] = (files[PATHS.mcpJson] ?? "").replace(
      '"command": "uvx",',
      '"command": "uvx",\n      "enabled": false,',
    );

    const report = await run(ports, true);
    expect(report.outcome).toBe("conflict");
    expect(report.mcpJson.outcome).toBe("conflict");
    expect(report.message).toContain("disabledServers");
  });

  test("an unreadable mcp.json is a conflict, and nothing is written", async () => {
    const { ports, files, links } = fakePorts({ files: { [PATHS.mcpJson]: "{ nope" } });
    const report = await run(ports, true);
    expect(report.outcome).toBe("conflict");
    expect(report.mcpJson.invalid).toBeDefined();
    expect(report.message).toContain("could not be read as a JSON object");
    expect(files[PATHS.mcpJson]).toBe("{ nope");
    expect(links).toEqual({});
  });
});

describe("the extension link", () => {
  test("extensions/jig.ts → the adapter's index.ts, created with the directory; yoki's links and the rest are named, not touched", async () => {
    const { ports, links, dirs } = fakePorts(YOKI_SWITCH_MACHINE);
    const dry = await run(ports);
    expect(dry.extensions.link).toEqual({
      path: `${PATHS.extensionsDir}/${OMP_EXTENSION_LINK_NAME}`,
      target: EXTENSION,
      state: "create",
    });
    expect(dry.extensions.yokiLeftovers.map((e) => e.name)).toEqual([
      "yoki-bridge.ts",
      "yoki-guard.ts",
    ]);
    expect(dry.extensions.foreign).toEqual([{ name: "orca-prefill.ts", what: "a regular file" }]);

    await run(ports, true);
    expect(links[`${PATHS.extensionsDir}/jig.ts`]).toBe(EXTENSION);
    expect(links[`${PATHS.extensionsDir}/yoki-guard.ts`]).toBe(
      "/repo/config/omp/extensions/yoki-guard.ts",
    );
    expect(dirs.has(PATHS.extensionsDir)).toBe(false);
  });

  test("a missing extensions directory is created on write; a regular file jig.ts is kept aside", async () => {
    const { ports, links, files, dirs } = fakePorts({
      files: { [`${OMP}/extensions/jig.ts`]: "my own\n" },
    });
    const dry = await run(ports);
    expect(dry.extensions.link.state).toBe("backup-then-create");
    await run(ports, true);
    expect(files[`${OMP}/extensions/jig.ts.pre-jig.20260923-000000`]).toBe("my own\n");
    expect(links[`${OMP}/extensions/jig.ts`]).toBe(EXTENSION);

    const fresh = fakePorts();
    expect((await run(fresh.ports)).extensions.dirState).toEqual({ kind: "missing" });
    await run(fresh.ports, true);
    expect(fresh.dirs.has(PATHS.extensionsDir)).toBe(true);
    expect(fresh.links[`${OMP}/extensions/jig.ts`]).toBe(EXTENSION);
    void dirs;
  });
});

describe("config.yml", () => {
  test("a new file gets jig's keys and omp's starting values, as YAML", async () => {
    const { ports, files } = fakePorts();
    const report = await run(ports, true);
    expect(report.configYml.outcome).toBe("write");
    const written = Bun.YAML.parse(files[`${OMP}/config.yml`] ?? "") as Record<string, unknown>;
    expect(written.modelRoles).toMatchObject({ default: "proxy/main", slow: "proxy/complex" });
    expect(written.statusLine).toMatchObject({ preset: "custom" });
    expect(written.symbolPreset).toBe("unicode");
    expect(files[`${OMP}/config.yml`]).not.toMatch(/ \n/);
  });

  test("omp's own keys are carried; a second apply after omp rewrote the file is a noop", async () => {
    const { ports, files } = fakePorts();
    await run(ports, true);
    // omp rewrites the file its own way and changes the theme
    const rewritten = Bun.YAML.parse(files[`${OMP}/config.yml`] ?? "") as Record<string, unknown>;
    files[`${OMP}/config.yml`] = JSON.stringify({ ...rewritten, theme: { dark: "dracula" } });
    const again = await run(ports, true);
    expect(again.configYml.outcome).toBe("noop");
    expect(again.configYml.carried).toContain("theme");
  });

  test("a hand edit of a key jig owns stops the write", async () => {
    const { ports, files } = fakePorts();
    await run(ports, true);
    const rewritten = Bun.YAML.parse(files[`${OMP}/config.yml`] ?? "") as Record<string, unknown>;
    files[`${OMP}/config.yml`] = JSON.stringify({
      ...rewritten,
      modelRoles: { default: "anthropic/x" },
    });
    const report = await run(ports, true);
    expect(report.outcome).toBe("conflict");
    expect(report.message).toContain("config.yml's jig keys");
  });

  test("text that is not YAML is a conflict, never overwritten", async () => {
    const { ports, files } = fakePorts();
    files[`${OMP}/config.yml`] = "a: [unclosed\n";
    const report = await run(ports, true);
    expect(report.configYml.invalid).toBeDefined();
    expect(files[`${OMP}/config.yml`]).toBe("a: [unclosed\n");
  });
});

describe("yoki leftovers under the agent directory", () => {
  test("each that exists is named with what it is, and none is touched by a write", async () => {
    const { ports, files } = fakePorts(YOKI_SWITCH_MACHINE);
    const report = await run(ports, true);
    expect(report.yokiLeftovers.map((l) => `${l.name}:${l.what}`)).toEqual([
      "yoki-hooks.json:a regular file",
      "RULES.md:a regular file",
      ".yoki:a directory",
    ]);
    expect(files[`${OMP}/RULES.md`]).toBe("<!-- yoki:begin -->\n");
  });

  test("a clean agent directory reports none", async () => {
    const { ports } = fakePorts();
    expect((await run(ports)).yokiLeftovers).toEqual([]);
  });
});

describe("--write delivers everything in one run", () => {
  test("links, files, mcp.json, manifest and provenance; then a second apply is a noop", async () => {
    const { ports, files, links, manifest, provenance } = fakePorts(YOKI_SWITCH_MACHINE);
    const first = await run(ports, true);

    expect(first.wrote).toBe(true);
    expect(links[`${AGENTS_SKILLS}/writeup`]).toBe(`${H}/skills/writeup`);
    expect(links[`${AGENTS_SKILLS}/grilling`]).toBe(`${H}/skills/grilling`);
    expect(links[`${AGENTS_SKILLS}/retired`]).toBeUndefined();
    expect(files[`${PATHS.agentsDir}/scout.md`]).toContain('name: "scout"');
    expect(manifest[PATHS.mcpJson]).toBe(ports.sha256(first.mcpJson.block));
    expect(manifest[`${PATHS.agentsDir}/scout.md`]).toBeDefined();
    expect(provenance[OMP]?.sourceFile).toBe(PATHS.mcpServers);

    const second = await run(ports, true);
    expect(second.outcome).toBe("noop");
    expect(second.mcpJson.outcome).toBe("noop");
    expect(second.agents.files.every((f) => f.outcome === "noop")).toBe(true);
    expect(second.extensions.link.state).toBe("ok");
  });
});

describe("a missing source is an error, not an empty result", () => {
  test("no MCP source", async () => {
    const { ports, files } = fakePorts();
    delete files[PATHS.mcpServers];
    expect(run(ports)).rejects.toThrow("MCP source not found");
  });
});
