# Dracula
set -g @theme_accent  "#bd93f9"
set -g @theme_accent2 "#50fa7b"
set -g @theme_fg      "#f8f8f2"
set -g @theme_muted   "#6272a4"
set -g @theme_surface "#44475a"
set -g @theme_crust   "#282a36"
set -g @theme_warn    "#ff5555"
