# Everforest Dark
set -g @theme_accent  "#7fbbb3"
set -g @theme_accent2 "#a7c080"
set -g @theme_fg      "#d3c6aa"
set -g @theme_muted   "#5c6a72"
set -g @theme_surface "#3d484d"
set -g @theme_crust   "#2e383c"
set -g @theme_warn    "#e67e80"
