# Gruvbox Dark
set -g @theme_accent  "#83a598"
set -g @theme_accent2 "#b8bb26"
set -g @theme_fg      "#ebdbb2"
set -g @theme_muted   "#665c54"
set -g @theme_surface "#3c3836"
set -g @theme_crust   "#282828"
set -g @theme_warn    "#fb4934"
