# Kanagawa
set -g @theme_accent  "#7e9cd8"
set -g @theme_accent2 "#7fb4ca"
set -g @theme_fg      "#dcd7ba"
set -g @theme_muted   "#54546d"
set -g @theme_surface "#2a2a37"
set -g @theme_crust   "#1f1f28"
set -g @theme_warn    "#c34043"
