# Nord
set -g @theme_accent  "#81a1c1"
set -g @theme_accent2 "#88c0d0"
set -g @theme_fg      "#d8dee9"
set -g @theme_muted   "#4c566a"
set -g @theme_surface "#3b4252"
set -g @theme_crust   "#2e3440"
set -g @theme_warn    "#bf616a"
