# Rose Pine
set -g @theme_accent  "#31748f"
set -g @theme_accent2 "#ebbcba"
set -g @theme_fg      "#e0def4"
set -g @theme_muted   "#6e6a86"
set -g @theme_surface "#26233a"
set -g @theme_crust   "#191724"
set -g @theme_warn    "#eb6f92"
