# .zshrc
# Generated by Dotfiles Manager

# 1. Initialize Core
# -----------------------------------------------------------------------------
export DOTFILES_ROOT="${HOME}/dotfiles" # Adjust if symlinked differently
# If this file is symlinked from domains/terminal/home/.zshrc, we need to find the repo root.
# Assuming standard install: ~/dotfiles/dotfiles
if [[ -d "$HOME/go/github.com/esh2n/dotfiles/dotfiles" ]]; then
    export DOTFILES_ROOT="$HOME/go/github.com/esh2n/dotfiles/dotfiles"
fi

# Source Loader
if [[ -f "${DOTFILES_ROOT}/core/install/loader.sh" ]]; then
    source "${DOTFILES_ROOT}/core/install/loader.sh"
else
    echo "⚠️ Dotfiles Core not found at ${DOTFILES_ROOT}"
fi

# 2. Load Domain Configs
# -----------------------------------------------------------------------------
# Load all shell fragments from domains
load_domain_shell_configs "${DOTFILES_ROOT}" "exports"
load_domain_shell_configs "${DOTFILES_ROOT}" "aliases"
load_domain_shell_configs "${DOTFILES_ROOT}" "functions"
load_domain_shell_configs "${DOTFILES_ROOT}" "options"

# 3. Lazy Load Tools
# -----------------------------------------------------------------------------
setup_lazy_mise

# 4. Local Config
# -----------------------------------------------------------------------------
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

# 5. Starship (Final Prompt)
# -----------------------------------------------------------------------------
if command -v starship >/dev/null; then
    eval "$(starship init zsh)"
fi
