-- AstroVim colorscheme - auto-generated by theme-switch
return {
  {
    "catppuccin/nvim",
    name = "catppuccin",
    lazy = true,
    opts = { transparent_background = true },
  },
  {
    "folke/tokyonight.nvim",
    lazy = true,
    opts = { transparent = true },
  },
  {
    "rebelot/kanagawa.nvim",
    lazy = true,
    opts = { transparent = true },
  },
  {
    "ellisonleao/gruvbox.nvim",
    lazy = true,
    opts = { transparent_mode = true },
  },
  {
    "Mofiqul/dracula.nvim",
    lazy = true,
    opts = { transparent_bg = true },
  },
  {
    "rose-pine/neovim",
    name = "rose-pine",
    lazy = true,
    opts = { styles = { transparency = true } },
  },
  {
    "sainnhe/everforest",
    lazy = true,
    init = function()
      vim.g.everforest_transparent_background = 1
    end,
  },
  {
    "navarasu/onedark.nvim",
    lazy = true,
    opts = { transparent = true },
  },
  {
    "maxmx03/solarized.nvim",
    lazy = true,
    opts = { transparent = { enabled = true } },
  },
  {
    "shaunsingh/nord.nvim",
    lazy = true,
    init = function()
      vim.g.nord_disable_background = true
    end,
  },
  {
    "AstroNvim/astrocore",
    opts = {
      colorscheme = "nord",
    },
  },
}
