# Auto-generated by theme-switch — do not edit
export THEME_NAME="nord"
export THEME_VARIANT="dark"

# Claude Code statusline
export CLAUDE_STATUSLINE_COLOR="cyan"
export CLAUDE_STATUSLINE_COLOR_HEX="#4070c0"

# bat
export BAT_THEME="ansi"

# fzf
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --color=bg+:#303030,bg:#202020,spinner:#50a0a0,hl:#4070c0 \
  --color=fg:#e0e0e0,header:#4070c0,info:#a070c0,pointer:#50a0a0 \
  --color=marker:#70a060,fg+:#e0e0e0,prompt:#a070c0,hl+:#4070c0 \
  --color=selected-bg:#404040"

# ripgrep (resolve path at source time via DOTFILES_ROOT)
_theme_env_dir="${DOTFILES_ROOT:-$HOME/dotfiles}/home/shared/theme/env"
export RIPGREP_CONFIG_PATH="${_theme_env_dir}/ripgreprc"
unset _theme_env_dir
