# Auto-generated by theme-switch — do not edit
export THEME_NAME="catppuccin-latte"
export THEME_VARIANT="light"

# Claude Code statusline
export CLAUDE_STATUSLINE_COLOR="lavender"
export CLAUDE_STATUSLINE_COLOR_HEX="#2050a0"

# bat
export BAT_THEME="ansi"

# fzf
export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
  --color=bg+:#d8d8d8,bg:#f4f4f4,spinner:#207070,hl:#2050a0 \
  --color=fg:#303030,header:#2050a0,info:#8040a0,pointer:#207070 \
  --color=marker:#408030,fg+:#303030,prompt:#8040a0,hl+:#2050a0 \
  --color=selected-bg:#c8c8c8"

# ripgrep (resolve path at source time via DOTFILES_ROOT)
_theme_env_dir="${DOTFILES_ROOT:-$HOME/dotfiles}/home/shared/theme/env"
export RIPGREP_CONFIG_PATH="${_theme_env_dir}/ripgreprc"
unset _theme_env_dir
