[directory]
home_symbol = "(🏠)"
truncation_length = 3
truncation_symbol = "(📁)/"
truncate_to_repo = true

[aws.region_aliases]
ap-northeast-1 = "jp"
[aws]
symbol = "🌥 "

[gcloud]
symbol = "️🌥 "
format = 'on [$symbol\($project\)]($style) '
[gcloud.region_aliases]
us-central1 = "uc1"
asia-northeast1 = "jp"