# AeroSpace Configuration

# Start AeroSpace at login
start-at-login = true

# Start borders
after-startup-command = ['exec-and-forget borders']

[gaps]
inner.horizontal = 10
inner.vertical = 10
outer.left = 10
outer.bottom = 10
outer.top = 10
outer.right = 10

[mode.main.binding]
# Basic window management
alt-h = 'focus left'
alt-j = 'focus down'
alt-k = 'focus up'
alt-l = 'focus right'

# Window movement
alt-shift-h = 'move left'
alt-shift-j = 'move down'
alt-shift-k = 'move up'
alt-shift-l = 'move right'

# Layout management
alt-slash = 'layout tiles horizontal vertical'
alt-comma = 'layout accordion horizontal vertical'

# Window resizing
alt-shift-minus = 'resize smart -50'
alt-shift-equal = 'resize smart +50'

# Workspace management
alt-tab = 'workspace-back-and-forth'
alt-shift-tab = 'move-workspace-to-monitor --wrap-around next'

# Workspace shortcuts
alt-1 = 'workspace 1'
alt-2 = 'workspace 2'
alt-3 = 'workspace 3'
alt-4 = 'workspace 4'
alt-5 = 'workspace 5'
alt-n = 'workspace N'  # Notion用ワークスペース
alt-s = 'workspace S'  # Slack用ワークスペース

# Move windows to workspaces
alt-shift-1 = ['move-node-to-workspace 1', 'workspace 1']
alt-shift-2 = ['move-node-to-workspace 2', 'workspace 2']
alt-shift-3 = ['move-node-to-workspace 3', 'workspace 3']
alt-shift-4 = ['move-node-to-workspace 4', 'workspace 4']
alt-shift-5 = ['move-node-to-workspace 5', 'workspace 5']
alt-shift-n = ['move-node-to-workspace N', 'workspace N']  # Notion用ワークスペース
alt-shift-s = ['move-node-to-workspace S', 'workspace S']  # Slack用ワークスペース

# Service mode
alt-shift-semicolon = 'mode service'

# App-specific workspace assignments
[[on-window-detected]]
if.app-id = 'com.tinyspeck.slackmacgap'
run = 'move-node-to-workspace S'

[[on-window-detected]]
if.app-id = 'notion.id'
run = 'move-node-to-workspace N'

[mode.service.binding]
esc = ['reload-config', 'mode main']
r = ['flatten-workspace-tree', 'mode main']  # reset layout
f = ['layout floating tiling', 'mode main']  # Toggle between floating and tiling layout
backspace = ['close-all-windows-but-current', 'mode main']
