package theme

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

// The texts below are the old theme-switch's heredocs, byte for byte, so a
// machine switched by either writes the same files
// (tests/services/theme-parity.bats).

const nvimPlugins = `  {
    "catppuccin/nvim",
    name = "catppuccin",
    lazy = true,
    opts = { transparent_background = true },
  },
  {
    "folke/tokyonight.nvim",
    lazy = true,
    opts = { transparent = true },
  },
  {
    "rebelot/kanagawa.nvim",
    lazy = true,
    opts = { transparent = true },
  },
  {
    "ellisonleao/gruvbox.nvim",
    lazy = true,
    opts = { transparent_mode = true },
  },
  {
    "Mofiqul/dracula.nvim",
    lazy = true,
    opts = { transparent_bg = true },
  },
  {
    "rose-pine/neovim",
    name = "rose-pine",
    lazy = true,
    opts = { styles = { transparency = true } },
  },
  {
    "sainnhe/everforest",
    lazy = true,
    init = function()
      vim.g.everforest_transparent_background = 1
    end,
  },
  {
    "navarasu/onedark.nvim",
    lazy = true,
    opts = { transparent = true },
  },
  {
    "maxmx03/solarized.nvim",
    lazy = true,
    opts = { transparent = { enabled = true } },
  },
  {
    "shaunsingh/nord.nvim",
    lazy = true,
    init = function()
      vim.g.nord_disable_background = true
    end,
  },
`

func lazyStyle(title, host, name string) string {
	return "-- " + title + " colorscheme - auto-generated by theme-switch\nreturn {\n" + nvimPlugins +
		"  {\n    \"" + host + "\",\n    opts = {\n      colorscheme = \"" + name + "\",\n    },\n  },\n}\n"
}

// writeOrSet rewrites the value in an existing file, or creates the file when
// dirMustExist does (a distribution not on this machine is left alone).
func writeOrSet(path string, re *regexp.Regexp, repl, dirMustExist string, create func() string) error {
	if exists(path) {
		_, err := rewrite(path, re, repl)
		return err
	}
	if !exists(dirMustExist) {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return err
	}
	return os.WriteFile(path, []byte(create()), 0o644)
}

func applyNeovim(e Env, name string) error {
	cfg := e.repo("domains/dev/config")
	colorscheme := regexp.MustCompile(`colorscheme = "[^"]*"`)
	set := fmt.Sprintf(`colorscheme = "%s"`, name)
	if err := writeOrSet(filepath.Join(cfg, "nvim-lazyvim/lua/plugins/colorscheme.lua"), colorscheme, set,
		filepath.Join(cfg, "nvim-lazyvim/lua/plugins"),
		func() string { return lazyStyle("LazyVim", "LazyVim/LazyVim", name) }); err != nil {
		return err
	}
	nvchad := or(nvchadThemes, name, "catppuccin")
	if err := writeOrSet(filepath.Join(cfg, "nvim-nvchad/lua/chadrc.lua"), regexp.MustCompile(`theme = "[^"]*"`),
		fmt.Sprintf(`theme = "%s"`, nvchad), filepath.Join(cfg, "nvim-nvchad"), func() string {
			return "-- NvChad config - auto-generated by theme-switch\nlocal M = {}\n\nM.base46 = {\n  theme = \"" +
				nvchad + "\",\n}\n\nreturn M\n"
		}); err != nil {
		return err
	}
	if err := writeOrSet(filepath.Join(cfg, "nvim-astrovim/lua/plugins/colorscheme.lua"), colorscheme, set,
		filepath.Join(cfg, "nvim-astrovim/lua/plugins"),
		func() string { return lazyStyle("AstroVim", "AstroNvim/astrocore", name) }); err != nil {
		return err
	}
	// lua/custom/plugins/colorscheme.lua made lazy.nvim fail ("Invalid plugin
	// spec"): the file lives outside plugins/ now.
	_ = os.Remove(filepath.Join(cfg, "nvim-custom/lua/custom/plugins/colorscheme.lua"))
	return writeOrSet(filepath.Join(cfg, "nvim-custom/lua/custom/colorscheme.lua"),
		regexp.MustCompile(`vim\.cmd\.colorscheme '[^']*'`), fmt.Sprintf("vim.cmd.colorscheme '%s'", name),
		filepath.Join(cfg, "nvim-custom/lua/custom"), func() string {
			return "-- Custom nvim colorscheme - auto-generated by theme-switch\n" +
				"-- This file is generated automatically and should not be committed\n" +
				"return {\n  load = function()\n    vim.cmd.colorscheme '" + name + "'\n  end,\n}\n"
		})
}

// applyCLI writes what the shells source (fzf, bat, ripgrep, the Claude Code
// statusline colour), delta's include and tmux-pane-border's colours.
func applyCLI(e Env, name string) error {
	p, err := readPalette(e.repo(Apps[0].Source(name)))
	if err != nil {
		return err
	}
	h := p.Hex
	env := e.repo("domains/system/config/theme-env")
	if err := os.MkdirAll(env, 0o755); err != nil {
		return err
	}
	status := or(statuslineColors, name, "orange")
	sh := strings.Join([]string{
		"# Auto-generated by theme-switch — do not edit",
		fmt.Sprintf(`export THEME_NAME="%s"`, name),
		fmt.Sprintf(`export THEME_VARIANT="%s"`, p.Variant()),
		"",
		"# Claude Code statusline",
		fmt.Sprintf(`export CLAUDE_STATUSLINE_COLOR="%s"`, status),
		fmt.Sprintf(`export CLAUDE_STATUSLINE_COLOR_HEX="#%s"`, h("blue")),
		"",
		"# bat",
		`export BAT_THEME="ansi"`,
		"",
		"# fzf",
		`export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \`,
		fmt.Sprintf(`  --color=bg+:#%s,bg:#%s,spinner:#%s,hl:#%s \`, h("surface0"), h("base"), h("teal"), h("blue")),
		fmt.Sprintf(`  --color=fg:#%s,header:#%s,info:#%s,pointer:#%s \`, h("text"), h("blue"), h("mauve"), h("teal")),
		fmt.Sprintf(`  --color=marker:#%s,fg+:#%s,prompt:#%s,hl+:#%s \`, h("green"), h("text"), h("mauve"), h("blue")),
		fmt.Sprintf(`  --color=selected-bg:#%s"`, h("surface1")),
		"",
		"# ripgrep (resolve path at source time via DOTFILES_ROOT)",
		`_theme_env_dir="${DOTFILES_ROOT:-$HOME/dotfiles}/domains/system/config/theme-env"`,
		`export RIPGREP_CONFIG_PATH="${_theme_env_dir}/ripgreprc"`,
		"unset _theme_env_dir",
		"",
	}, "\n")
	fzf := fmt.Sprintf("--color=bg+:#%s,bg:#%s,spinner:#%s,hl:#%s --color=fg:#%s,header:#%s,info:#%s,pointer:#%s "+
		"--color=marker:#%s,fg+:#%s,prompt:#%s,hl+:#%s --color=selected-bg:#%s",
		h("surface0"), h("base"), h("teal"), h("blue"), h("text"), h("blue"), h("mauve"), h("teal"),
		h("green"), h("text"), h("mauve"), h("blue"), h("surface1"))
	fish := strings.Join([]string{
		"# Auto-generated by theme-switch — do not edit",
		fmt.Sprintf(`set -gx THEME_NAME "%s"`, name),
		fmt.Sprintf(`set -gx THEME_VARIANT "%s"`, p.Variant()),
		fmt.Sprintf(`set -gx CLAUDE_STATUSLINE_COLOR "%s"`, status),
		fmt.Sprintf(`set -gx CLAUDE_STATUSLINE_COLOR_HEX "#%s"`, h("blue")),
		`set -gx BAT_THEME "ansi"`,
		fmt.Sprintf(`set -gx FZF_DEFAULT_OPTS "$FZF_DEFAULT_OPTS %s"`, fzf),
		`if test -n "$DOTFILES_ROOT"`,
		`    set -gx RIPGREP_CONFIG_PATH "$DOTFILES_ROOT/domains/system/config/theme-env/ripgreprc"`,
		"else",
		`    set -gx RIPGREP_CONFIG_PATH "$HOME/dotfiles/domains/system/config/theme-env/ripgreprc"`,
		"end",
		"",
	}, "\n")
	rg := fmt.Sprintf("--colors=match:fg:%d\n--colors=line:fg:%d\n--colors=path:fg:%d\n",
		xterm256(h("red")), xterm256(h("yellow")), xterm256(h("blue")))
	for file, text := range map[string]string{"current.sh": sh, "current.fish": fish, "ripgreprc": rg} {
		if err := os.WriteFile(filepath.Join(env, file), []byte(text), 0o644); err != nil {
			return err
		}
	}

	syntax := "Dracula"
	if p.Light {
		syntax = "GitHub"
	}
	delta := strings.Join([]string{
		"# Auto-generated by theme-switch — do not edit",
		"[delta]",
		"    syntax-theme = " + syntax,
		fmt.Sprintf(`    minus-style = syntax "#%s"`, scaled(h("red"), 4)),
		fmt.Sprintf(`    minus-emph-style = syntax "#%s"`, scaled(h("red"), 2)),
		fmt.Sprintf(`    plus-style = syntax "#%s"`, scaled(h("green"), 4)),
		fmt.Sprintf(`    plus-emph-style = syntax "#%s"`, scaled(h("green"), 2)),
		fmt.Sprintf(`    line-numbers-minus-style = "#%s"`, h("red")),
		fmt.Sprintf(`    line-numbers-plus-style = "#%s"`, h("green")),
		fmt.Sprintf(`    line-numbers-zero-style = "#%s"`, h("overlay0")),
		fmt.Sprintf(`    hunk-header-decoration-style = "#%s" box`, h("blue")),
		"",
	}, "\n")
	git := filepath.Join(e.Home, ".config", "git")
	if err := os.MkdirAll(git, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(git, "delta-theme.gitconfig"), []byte(delta), 0o644); err != nil {
		return err
	}

	active, inactive := "#"+h("blue"), "#"+h("surface0")
	if b, err := os.ReadFile(e.repo("next/home/darwin/tmux/config/themes/" + name + ".conf")); err == nil {
		pick := func(key string) string {
			m := regexp.MustCompile(`(?m)^.*` + regexp.QuoteMeta(key) + `.*"(#[a-f0-9]{6})".*$`).FindSubmatch(b)
			if m == nil {
				return ""
			}
			return string(m[1])
		}
		if v := pick("@theme_accent2"); v != "" {
			active = v
		}
		if v := pick("@theme_surface"); v != "" {
			inactive = v
		}
	}
	pb := filepath.Join(e.Home, ".config", "tmux-pane-border")
	if !exists(pb) {
		return nil
	}
	border := fmt.Sprintf("# Auto-generated by theme-switch — do not edit\n[border]\nstyle = \"rounded\"\n"+
		"active_color = \"%s\"\ninactive_color = \"%s\"\npadding_top = 0\npadding_bottom = 0\n"+
		"padding_left = 1\npadding_right = 1\n", active, inactive)
	return os.WriteFile(filepath.Join(pb, "config.toml"), []byte(border), 0o644)
}
