import { describe, expect, test } from "bun:test";
import {
  codexAgentFileName,
  codexModelFor,
  parseAgentDefinition,
  renderCodexAgent,
  tomlString,
  toolsSentence,
} from "../../../src/domain/codex/agents";

const SOURCE = `---
name: research
description: Industry survey before a design decision. Use when "調べて".
tools: ["Read", "Grep", "WebFetch"]
model: sonnet
---

You survey how the industry actually does something.

## Rules

- Every claim carries a URL.
`;

describe("parseAgentDefinition", () => {
  test("reads the four fields and the body, frontmatter stripped", () => {
    const definition = parseAgentDefinition(SOURCE, "research");
    expect(definition).toEqual({
      name: "research",
      description: 'Industry survey before a design decision. Use when "調べて".',
      tools: ["Read", "Grep", "WebFetch"],
      model: "sonnet",
      body: "You survey how the industry actually does something.\n\n## Rules\n\n- Every claim carries a URL.",
    });
  });

  test("tools may be a comma-separated scalar or a block list; a quoted scalar is unquoted", () => {
    expect(parseAgentDefinition("---\ntools: Read, Grep\n---\nx\n", "a").tools).toEqual([
      "Read",
      "Grep",
    ]);
    expect(
      parseAgentDefinition("---\ntools:\n  - Read\n  - 'Bash'\nmodel: opus\n---\nx\n", "a"),
    ).toMatchObject({ tools: ["Read", "Bash"], model: "opus" });
    expect(parseAgentDefinition('---\nname: "quoted"\n---\nx\n', "a").name).toBe("quoted");
  });

  test("no frontmatter: the file stem names the agent and the whole text is the body", () => {
    expect(parseAgentDefinition("Just a prompt.\n", "plain")).toEqual({
      name: "plain",
      description: "",
      tools: [],
      body: "Just a prompt.",
    });
  });
});

describe("codexModelFor", () => {
  const MAP = { sonnet: "gpt-x-mid" };

  test("a mapped tier yields the Codex id; an unmapped one is a reported gap, never a guess", () => {
    expect(codexModelFor("sonnet", MAP)).toEqual({
      kind: "mapped",
      tier: "sonnet",
      model: "gpt-x-mid",
    });
    expect(codexModelFor("Sonnet", MAP)).toMatchObject({ kind: "mapped" });
    expect(codexModelFor("opus", MAP)).toEqual({ kind: "unmapped", tier: "opus" });
  });

  test("absent and `inherit` both mean: leave `model` out, and that is not a gap", () => {
    expect(codexModelFor(undefined, MAP)).toEqual({ kind: "inherit" });
    expect(codexModelFor("inherit", MAP)).toEqual({ kind: "inherit" });
  });
});

describe("renderCodexAgent", () => {
  const definition = parseAgentDefinition(SOURCE, "research");

  test("the three required keys, the tools sentence folded into the instructions, and valid TOML", () => {
    const toml = renderCodexAgent({
      definition,
      model: { kind: "unmapped", tier: "sonnet" },
      sourcePath: "/repo/llm/harness/agents/research.md",
    });
    expect(
      toml.startsWith(
        "# generated by jig apply --target codex from /repo/llm/harness/agents/research.md",
      ),
    ).toBe(true);
    expect(toml).toContain(
      "# format: https://learn.chatgpt.com/docs/agent-configuration/subagents",
    );
    expect(toml).not.toContain("\nmodel = ");

    const parsed = Bun.TOML.parse(toml) as Record<string, unknown>;
    expect(parsed.name).toBe("research");
    expect(parsed.description).toBe(definition.description);
    expect(parsed.developer_instructions).toBe(
      `${definition.body}\n\n${toolsSentence(definition.tools)}`,
    );
    expect(String(parsed.developer_instructions)).toContain("Read, Grep, WebFetch");
  });

  test("a mapped model is written between description and the instructions", () => {
    const toml = renderCodexAgent({
      definition,
      model: { kind: "mapped", tier: "sonnet", model: "gpt-x-mid" },
      sourcePath: "/s.md",
    });
    expect(toml).toContain('\nmodel = "gpt-x-mid"\n');
    expect(toml.indexOf("model =")).toBeLessThan(toml.indexOf("developer_instructions ="));
  });

  test("no tools: no sentence, the body alone", () => {
    const toml = renderCodexAgent({
      definition: { ...definition, tools: [] },
      model: { kind: "inherit" },
      sourcePath: "/s.md",
    });
    expect((Bun.TOML.parse(toml) as Record<string, unknown>).developer_instructions).toBe(
      definition.body,
    );
  });
});

describe("tomlString", () => {
  test("round-trips quotes, backslashes, newlines, DEL, the Unicode line separators and non-ASCII through Codex's parser", () => {
    const text = `say "hi"\\ \n\ttab ${String.fromCharCode(0x7f)} 決定 ${String.fromCharCode(0x2028)}${String.fromCharCode(0x2029)}`;
    const literal = tomlString(text);
    expect(literal).toContain("\\u007F");
    expect(literal).toContain("\\u2028");
    const parsed = Bun.TOML.parse(`v = ${literal}`) as { v: string };
    expect(parsed.v).toBe(text);
  });
});

describe("codexAgentFileName", () => {
  test("keeps the source stem", () => {
    expect(codexAgentFileName("go-reviewer.md")).toBe("go-reviewer.toml");
  });
});
