import { describe, expect, test } from "bun:test";
import { modelChoiceFor, parseAgentDefinition } from "../../../src/domain/claude/agent-definition";
import {
  CLAUDE_TO_OMP_TOOL,
  ompAgentFileName,
  ompAgentFrontmatter,
  renderOmpAgent,
  translateTools,
  yamlString,
} from "../../../src/domain/omp/agents";

const SOURCE = `---
name: research
description: Industry survey before a design decision. Use when "調べて": quotes, colons.
tools: ["Read", "Grep", "WebFetch", "NotebookEdit", "Agent"]
model: sonnet
---

You survey how the industry actually does something.

## Rules

- Every claim carries a URL.
`;

/** omp's canonical ids (packages/coding-agent/src/tools/builtin-names.ts), the ones the table may name. */
const OMP_BUILTIN_TOOL_NAMES = new Set([
  "read",
  "bash",
  "edit",
  "ast_grep",
  "ast_edit",
  "ask",
  "debug",
  "eval",
  "github",
  "glob",
  "grep",
  "find",
  "lsp",
  "checkpoint",
  "rewind",
  "context_notes",
  "new_context",
  "security_scan",
  "task",
  "hub",
  "todo",
  "web_search",
  "write",
  "memory_edit",
  "retain",
  "recall",
  "reflect",
  "learn",
  "manage_skill",
]);

describe("translateTools", () => {
  test("every right-hand side of the table is an omp built-in id", () => {
    for (const id of Object.values(CLAUDE_TO_OMP_TOOL)) {
      expect(OMP_BUILTIN_TOOL_NAMES.has(id)).toBe(true);
    }
  });

  test("maps Claude names, folds duplicates, and reports what has no omp tool — in source order", () => {
    expect(
      translateTools(["Read", "WebFetch", "Grep", "NotebookEdit", "Edit", "MultiEdit", "Skill"]),
    ).toEqual({
      tools: ["read", "grep", "edit"],
      unmapped: ["NotebookEdit", "Skill"],
    });
    expect(translateTools([])).toEqual({ tools: [], unmapped: [] });
  });
});

describe("renderOmpAgent", () => {
  const definition = parseAgentDefinition(SOURCE, "research");
  const tools = translateTools(definition.tools);

  test("omp's frontmatter — name and description verbatim, tools as omp ids, model only when mapped — then the body verbatim", () => {
    const text = renderOmpAgent({
      definition,
      model: modelChoiceFor("sonnet", {}),
      tools,
      sourcePath: "/repo/llm/harness/agents/research.md",
    });
    expect(text).toBe(
      [
        "---",
        "# generated by jig apply --target omp from /repo/llm/harness/agents/research.md — edit the source, not this file",
        "# format: https://github.com/can1357/oh-my-pi/blob/main/docs/task-agent-discovery.md",
        'name: "research"',
        'description: "Industry survey before a design decision. Use when \\"調べて\\": quotes, colons."',
        "tools: [read, grep, task]",
        "---",
        "",
        "You survey how the industry actually does something.",
        "",
        "## Rules",
        "",
        "- Every claim carries a URL.",
        "",
      ].join("\n"),
    );
    expect(text).not.toContain("\nmodel:");
    expect(text.endsWith(`${definition.body}\n`)).toBe(true);
  });

  test("the frontmatter parses as YAML with the same fields omp reads (parseAgentFields)", () => {
    const text = renderOmpAgent({
      definition,
      model: { kind: "mapped", tier: "sonnet", model: "@review" },
      tools,
      sourcePath: "/s.md",
    });
    const parsed = Bun.YAML.parse(ompAgentFrontmatter(text)) as Record<string, unknown>;
    expect(parsed.name).toBe("research");
    expect(parsed.description).toBe(definition.description);
    expect(parsed.model).toBe("@review");
    expect(parsed.tools).toEqual(["read", "grep", "task"]);
    expect(text.indexOf("model:")).toBeLessThan(text.indexOf("tools:"));
  });

  test("no surviving tool: the key is omitted so omp grants its default set", () => {
    const text = renderOmpAgent({
      definition,
      model: { kind: "inherit" },
      tools: { tools: [], unmapped: ["NotebookEdit"] },
      sourcePath: "/s.md",
    });
    expect(text).not.toContain("tools:");
    expect(text).not.toContain("model:");
  });
});

describe("yamlString", () => {
  test("round-trips quotes, backslashes, colons, newlines and non-ASCII through Bun's YAML parser", () => {
    const value = 'say "hi"\\ key: value\n\ttab 決定 #not-a-comment';
    expect((Bun.YAML.parse(`v: ${yamlString(value)}`) as { v: string }).v).toBe(value);
  });
});

describe("ompAgentFileName", () => {
  test("keeps the source file name: omp's format is the source's", () => {
    expect(ompAgentFileName("go-reviewer.md")).toBe("go-reviewer.md");
  });
});
