# Catppuccin Mocha
set -g @theme_accent  "#cba6f7"
set -g @theme_accent2 "#89b4fa"
set -g @theme_fg      "#cdd6f4"
set -g @theme_muted   "#6c7086"
set -g @theme_surface "#313244"
set -g @theme_crust   "#11111b"
set -g @theme_warn    "#f38ba8"
