hide_agent_reasoning = true
network_access = true

# macOS notification when a task completes
notify = ["bash", "-lc", "afplay /System/Library/Sounds/Ping.aiff"]
model = "gpt-5-codex"

[tools]
web_search = true

[mcp_servers.context7]
type = "stdio"
command = "npx"
args = ["-y", "@upstash/context7-mcp@1.0.14"]

[mcp_servers.figma]
command = "npx"
args = ["tsx", "./.tmp/mcp/FigmaMCP/src/index.ts"]
[mcp_servers.figma.env]
FIGMA_API_KEY = ""

[mcp_servers.notion-mcp]
command = ""
type = "http"
url = "https://mcp.notion.com/mcp"

[mcp_servers.container-use]
type = "stdio"
command = "container-use"
args = ["stdio"]

[mcp_servers.terraform]
type = "stdio"
command = "/go/bin/terraform-mcp-server"
args = ["stdio"]

[mcp_servers.playwright]
type = "stdio"
command = "npx"
args = ["-y", "@playwright/mcp@0.0.32"]

[mcp_servers.serena]
type = "stdio"
command = "uvx"
args = [
  "--from",
  "git+https://github.com/oraios/serena@v0.1.3",
  "serena",
  "start-mcp-server",
  "--context",
  "ide-assistant",
]

[projects."/Users/shunya.endo/go/github.com/esh2n/dotfiles"]
trust_level = "trusted"

[projects."/Users/shunya.endo/go/github.com/sansaninc/sdi-core"]
trust_level = "trusted"
