'use strict';

/**
 * Converts a merged permission layer set (see parse.js) into the Codex CLI
 * artifacts described in scratchpad spike S3 §4: an execpolicy `.rules`
 * file, the `[permissions.yoki]` filesystem-deny TOML table, and the list
 * of patterns that still need a Codex hook because neither mechanism can
 * express them (S3 §2, §4c).
 *
 * This only covers the `Bash(...)` / `Read(...)` shapes that the S3 mapping
 * actually classified — a pattern shape S3 never saw (e.g. a pack's
 * MCP-tool pattern) falls through as unmapped rather than guessed at.
 */

const { loadAndMerge } = require('./parse');
const { hookEnforcedDeny, mergeGuardDeny } = require('./guard-deny');

const BASH_PATTERN_RE = /^Bash\((.+)\)$/;
const READ_SECRET_PATTERN_RE = /^Read\((.+)\)$/;

/** Splits a Bash(...) pattern's inner text into execpolicy tokens, or null
 * when the text contains shell constructs (redirection, standalone glob
 * tokens) execpolicy's token-exact prefix matcher cannot see — S3 §1
 * "Shell scripts / compound commands". */
function toExecpolicyTokens(inner) {
  if (/[><|&;$]/.test(inner)) return null; // redirection / substitution / compound

  const isPrefix = inner.endsWith(' *');
  const body = isPrefix ? inner.slice(0, -2) : inner;
  const tokens = body.split(/\s+/).filter(Boolean);

  if (tokens.some(t => t.includes('*') || t.includes('?'))) return null; // glob token, not a prefix marker

  return { tokens, isPrefix };
}

function starlarkList(tokens) {
  return `[${tokens.map(t => JSON.stringify(t)).join(', ')}]`;
}

/**
 * @param {{allow: Array<{pattern:string, reason?:string}>, deny: Array<{pattern:string, reason?:string}>}} merged
 * @returns {{rules: string, hookEnforced: Array<{pattern:string, reason:string}>}}
 */
function toRules(merged) {
  const lines = [
    '# ~/.codex/rules/yoki.rules — GENERATED by yoki-switch from claude-profiles',
    '# permissions.yaml (runtime/yoki/scripts/lib/permissions/to-codex.js). Do not edit by hand.',
    '# Semantics: token-exact prefix match; nested list = alternatives; forbidden > prompt > allow.',
    '',
  ];
  const hookEnforced = [];

  const denyRules = [];
  for (const entry of merged.deny) {
    const m = BASH_PATTERN_RE.exec(entry.pattern);
    if (!m) continue; // Read/Edit denies are handled by the fs-permissions table, not rules
    const parsed = toExecpolicyTokens(m[1]);
    if (!parsed) {
      hookEnforced.push({ pattern: entry.pattern, reason: entry.reason || '' });
      continue;
    }
    const justification = entry.reason ? `yoki: ${entry.reason}` : `yoki: ${entry.pattern} is denied`;
    denyRules.push(`prefix_rule(pattern=${starlarkList(parsed.tokens)}, decision="forbidden", justification=${JSON.stringify(justification)})`);
  }

  const allowRules = [];
  for (const entry of merged.allow) {
    const m = BASH_PATTERN_RE.exec(entry.pattern);
    if (!m) continue; // tool-level allows (Read(**), Task(**), ...) have no execpolicy equivalent
    const parsed = toExecpolicyTokens(m[1]);
    if (!parsed) continue; // e.g. `* --version` — no wildcard first token in execpolicy (S3 §2b row 61-62)
    allowRules.push(`prefix_rule(pattern=${starlarkList(parsed.tokens)}, decision="allow")`);
  }

  lines.push('# ---- forbidden (deny layer) ----------------------------------------------');
  lines.push(...denyRules);
  lines.push('');
  lines.push('# ---- allow (only relevant under untrusted / on-request) -------------------');
  lines.push(...allowRules);
  lines.push('');

  return { rules: lines.join('\n'), hookEnforced };
}

/**
 * Read(...) deny patterns become `[permissions.yoki.filesystem]` entries —
 * the 14 secret-path rows in S3 §2a. Any other Read pattern (workspace-root
 * globs like a double-star `.env` glob) is left out: it belongs under
 * `[permissions.yoki.filesystem.":workspace_roots"]`, which needs the
 * pattern to be a workspace-relative glob, not a bare Claude path — S3 §4b
 * hand-wrote those since there are only a handful and they don't come from
 * the per-machine secret-path list this converts.
 */
function toFilesystemDenyEntries(merged) {
  const entries = [];
  for (const entry of merged.deny) {
    const m = READ_SECRET_PATTERN_RE.exec(entry.pattern);
    if (!m) continue;
    const inner = m[1];
    if (inner.startsWith('**') ) continue; // workspace-relative glob, not an absolute/~ path
    entries.push(inner);
  }
  return entries;
}

/**
 * The same absolute/`~`-rooted `Read(...)` denies `toFilesystemDenyEntries`
 * writes into `[permissions.yoki.filesystem]`, as full `{pattern, reason}`
 * guard entries.
 *
 * These are carried by BOTH layers on Codex, not moved between them. The
 * filesystem table is the declarative layer; it is authoritative only while
 * Codex is actually consulting it. Under
 * `--dangerously-bypass-approvals-and-sandbox` that table is off, while hooks
 * still run — a PreToolUse `permissionDecision: deny` is honoured even in
 * `bypassPermissions` mode (measured on codex-cli 0.152.0, see the
 * codex-read-deny spike). Combined with the fact that Codex has no dedicated
 * read tool — a file read shells out as `cat`/`sed`, which the filesystem
 * table does not gate at all — the hook is the layer that survives, so it has
 * to know these patterns too or `cat ~/.ssh/id_ed25519` goes unguarded.
 *
 * @returns {Array<{pattern:string, reason:string}>}
 */
function toFilesystemReadDeny(merged) {
  const expressed = new Set(toFilesystemDenyEntries(merged));
  const out = [];
  for (const entry of merged.deny) {
    const m = READ_SECRET_PATTERN_RE.exec(entry.pattern);
    if (!m || !expressed.has(m[1])) continue;
    out.push({ pattern: entry.pattern, reason: entry.reason || '' });
  }
  return out;
}

/**
 * @returns {string} the `[permissions.yoki]` TOML table (S3 §4b), extending
 * ":workspace" with filesystem read-denies for the secret-path entries.
 */
function toPermissionsToml(merged) {
  const fsEntries = toFilesystemDenyEntries(merged);
  const lines = [
    '# GENERATED by yoki-switch from claude-profiles permissions.yaml. Do not edit by hand.',
    'default_permissions = "yoki"',
    '',
    '[permissions.yoki]',
    'extends = ":workspace"',
    '',
    '[permissions.yoki.filesystem]',
  ];
  for (const path of fsEntries) {
    lines.push(`${JSON.stringify(path)} = "deny"`);
  }
  lines.push('');
  return lines.join('\n');
}

/**
 * Deny entries neither half of the Codex mapping expresses.
 *
 * `toRules` covers the `Bash(...)` denies it can tokenize (and reports the
 * rest as hook-enforced itself); `toFilesystemDenyEntries` covers the
 * absolute/`~`-rooted `Read(...)` denies. What is left over:
 *
 *   - `Read(**…)` workspace globs — deliberately excluded from the
 *     filesystem table (they need a workspace-relative form; see
 *     toFilesystemDenyEntries).
 *   - EVERY `Edit(...)` deny. The filesystem table is built from `Read(...)`
 *     patterns only, so `Edit(/etc/**)`, `Edit(~/.ssh/id_*)` and friends had
 *     no expression on Codex at all unless permissions.yaml happened to tag
 *     them `enforce: [hook]` — the four `*.pem`/`*.key`/`.env` rows did, the
 *     other seventeen did not.
 *   - anything else pattern-shaped (`WebFetch(domain:...)`).
 *
 * These are exactly the patterns hooks/pre-permission-guard.js has to carry
 * on Codex, so they are unioned into the guard deny list below.
 *
 * @returns {Array<{pattern:string, reason:string}>}
 */
function toUnexpressibleDeny(merged) {
  const expressedByFilesystem = new Set(
    toFilesystemDenyEntries(merged).map(inner => `Read(${inner})`)
  );

  const out = [];
  for (const entry of merged.deny) {
    if (BASH_PATTERN_RE.test(entry.pattern)) continue; // toRules owns these
    if (expressedByFilesystem.has(entry.pattern)) continue;
    out.push({ pattern: entry.pattern, reason: entry.reason || '' });
  }
  return out;
}

function convert(filePaths) {
  const merged = loadAndMerge(filePaths);
  const { rules, hookEnforced: rulesHookEnforced } = toRules(merged);

  // Union: an entry can be hook-enforced because the yaml says so (enforce:
  // [hook]) and/or because to-codex.js's own execpolicy translation found it
  // unexpressible — dedupe by pattern.
  const hookEnforced = mergeGuardDeny(hookEnforcedDeny(merged), rulesHookEnforced);

  // What the guard actually enforces on Codex: the above, PLUS every deny
  // neither yoki.rules nor [permissions.yoki.filesystem] expresses, PLUS the
  // absolute/`~`-rooted Read denies the filesystem table DOES express —
  // defense in depth, because that table is off under
  // --dangerously-bypass-approvals-and-sandbox (and never gated a shell
  // `cat` in the first place) while hooks keep running. See
  // toFilesystemReadDeny.
  const unexpressible = toUnexpressibleDeny(merged);
  const guardDeny = mergeGuardDeny(hookEnforced, unexpressible, toFilesystemReadDeny(merged));

  return {
    rules,
    permissions: toPermissionsToml(merged),
    hookEnforced,
    unexpressible,
    guardDeny,
  };
}

module.exports = { toRules, toFilesystemDenyEntries, toFilesystemReadDeny, toPermissionsToml, toUnexpressibleDeny, convert };

if (require.main === module) {
  const args = process.argv.slice(2);
  const sourcesFlagIndex = args.indexOf('--sources');
  if (sourcesFlagIndex === -1) {
    process.stderr.write('Usage: node to-codex.js --sources <layer.yaml>...\n');
    process.exit(1);
  }
  const filePaths = args.slice(sourcesFlagIndex + 1);
  try {
    process.stdout.write(JSON.stringify(convert(filePaths)));
  } catch (err) {
    process.stderr.write(`to-codex.js: ${err.message}\n`);
    process.exit(1);
  }
}
