[tools]
python = "3.12"
ruby = "latest"
node = "23.8.0"
go = "latest"
rust = "latest"
bun = "latest"
deno = "latest"

[settings]
experimental = false
verbose = false

[env]
PYTHONPATH = "${PYTHONPATH:-}:${PWD}"
GEM_HOME = "{{ env.HOME }}/.gem"
GOPATH = "{{ env.HOME }}/go"
GOBIN = "{{ env.HOME }}/go/bin"
CARGO_HOME = "{{ env.HOME }}/.cargo"
RUSTUP_HOME = "{{ env.HOME }}/.rustup"
DENO_INSTALL_ROOT = "{{ env.HOME }}/.deno"
BUN_INSTALL = "{{ env.HOME }}/.bun"
