[tools]
python = "3.12"
ruby = "latest"
node = "23.8.0"
go = "latest"
rust = "latest"
bun = "latest"
deno = "latest"
dotnet = "8.0.408"

[settings]
experimental = false
verbose = false

[env]
PYTHONPATH = "${PYTHONPATH:-}:${PWD}"
GEM_HOME = "/Users/esh2n/.gem"
GOPATH = "/Users/esh2n/go"
GOBIN = "${GOPATH}/bin"
GOROOT = ""
CARGO_HOME = "/Users/esh2n/.cargo"
RUSTUP_HOME = "/Users/esh2n/.rustup"
DENO_INSTALL_ROOT = "/Users/esh2n/.deno"
DOTNET_ROOT = "/Users/esh2n/.local/share/mise/installs/dotnet/8.0.408"
BUN_INSTALL = "/Users/esh2n/.bun"
