/**
 * `~/.codex/agents/<name>.toml`, one generated file per `agents/*.md`.
 *
 * The source is a Claude Code subagent: YAML frontmatter with `name`,
 * `description`, `tools` and `model`, then the system prompt as the body.
 * Codex's custom agent is a TOML file with three required keys and a few
 * optional ones (https://learn.chatgpt.com/docs/agent-configuration/subagents,
 * "Custom agents": `name`, `description`, `developer_instructions` required;
 * `model`, `model_reasoning_effort`, `sandbox_mode`, `mcp_servers`,
 * `skills.config` optional). The translation is one-to-one where a field
 * exists on both sides and explicit where it does not:
 *
 * - `name` and `description` are copied verbatim.
 * - the body becomes `developer_instructions`.
 * - `tools`: Codex has no per-agent tool list — the page names none, and a
 *   custom agent inherits the session's tools — so the list is rendered as
 *   one trailing sentence of the instructions rather than dropped.
 * - `model`: a Claude tier name (`haiku`/`sonnet`/`opus`) means nothing to
 *   Codex. It is looked up in a map the caller supplies; a tier the map does
 *   not know is left out, so Codex applies its own default, and reported.
 *   The generator never invents a Codex model id.
 *
 * The source parser and the model question are `../claude/agent-definition.ts`,
 * shared with the omp target; the Codex names below are kept for callers.
 *
 * Pure: text in, text out. The caller reads the file and validates the
 * result as TOML if it wants to.
 */

import {
  type AgentDefinition,
  type ModelChoice,
  modelChoiceFor,
  parseAgentDefinition,
} from "../claude/agent-definition";

export { parseAgentDefinition };
export type { AgentDefinition };

/** See `ModelChoice`: the same three answers, for a Codex model id. */
export type CodexModelChoice = ModelChoice;

export const codexModelFor: (
  tier: string | undefined,
  map: Readonly<Record<string, string>>,
) => CodexModelChoice = modelChoiceFor;

/**
 * A TOML basic string (https://toml.io/en/v1.0.0#string): `"` and `\`
 * escaped, every control character other than tab escaped (`\n` and `\r`
 * by name, the rest as `\uXXXX`, DEL included), tab and the rest of Unicode
 * raw. The two Unicode line separators are escaped as well: the spec allows
 * them raw, but Bun's parser — the one that validates the generated text
 * here — reads them as line ends. Not `JSON.stringify`, whose `\t` the same
 * parser decodes as a form feed; a raw tab is what the spec asks for anyway.
 */
export function tomlString(value: string): string {
  let out = '"';
  for (const char of value) {
    const code = char.codePointAt(0) ?? 0;
    if (char === '"') out += '\\"';
    else if (char === "\\") out += "\\\\";
    else if (char === "\n") out += "\\n";
    else if (char === "\r") out += "\\r";
    else if (char === "\t") out += char;
    else if (code < 0x20 || code === 0x7f || code === 0x2028 || code === 0x2029) {
      out += `\\u${code.toString(16).toUpperCase().padStart(4, "0")}`;
    } else out += char;
  }
  return `${out}"`;
}

export interface CodexAgentInput {
  readonly definition: AgentDefinition;
  readonly model: CodexModelChoice;
  /** Absolute path of the source `agents/<name>.md`, for the header comment. */
  readonly sourcePath: string;
}

/** The trailing sentence that carries `tools:` into a format that has no such field. */
export function toolsSentence(tools: readonly string[]): string {
  return tools.length === 0
    ? ""
    : `The source definition limits this agent to these tools: ${tools.join(", ")}. Codex has no per-agent tool list, so honour it as an instruction.`;
}

/** The whole `<name>.toml`. Required keys first, `model` only when mapped, instructions last. */
export function renderCodexAgent(input: CodexAgentInput): string {
  const { definition, model } = input;
  const sentence = toolsSentence(definition.tools);
  const instructions = sentence === "" ? definition.body : `${definition.body}\n\n${sentence}`;
  const lines = [
    `# generated by jig apply --target codex from ${input.sourcePath} — edit the source, not this file`,
    "# format: https://learn.chatgpt.com/docs/agent-configuration/subagents",
    `name = ${tomlString(definition.name)}`,
    `description = ${tomlString(definition.description)}`,
    ...(model.kind === "mapped" ? [`model = ${tomlString(model.model)}`] : []),
    `developer_instructions = ${tomlString(instructions)}`,
  ];
  return `${lines.join("\n")}\n`;
}

/** `research.md` → `research.toml`; the file name, not the frontmatter `name`, keys the destination. */
export function codexAgentFileName(sourceFile: string): string {
  return `${sourceFile.replace(/\.md$/, "")}.toml`;
}
